"""Migraciones versionadas, ligeras y compatibles con SQLite/Postgres."""

from __future__ import annotations

import argparse
from collections.abc import Callable
from datetime import datetime

from .clockin_integrity import clockin_seal


def _types(dialect: str) -> dict[str, str]:
    if dialect == "postgres":
        return {
            "id": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "ref": "BIGINT",
            "real": "DOUBLE PRECISION",
            "timestamp": "TIMESTAMP WITHOUT TIME ZONE",
            "boolean": "BOOLEAN",
        }
    return {
        "id": "INTEGER PRIMARY KEY AUTOINCREMENT",
        "ref": "INTEGER",
        "real": "REAL",
        "timestamp": "TEXT",
        "boolean": "INTEGER",
    }


def _initial_schema(dialect: str) -> str:
    t = _types(dialect)
    return f"""
CREATE TABLE IF NOT EXISTS businesses (
    id                      {t["id"]},
    name                    TEXT NOT NULL,
    owner_email             TEXT,
    sector                  TEXT,
    nif                     TEXT,
    address                 TEXT,
    default_vat             {t["real"]} NOT NULL DEFAULT 21,
    default_irpf            {t["real"]} NOT NULL DEFAULT 0,
    whatsapp_phone          TEXT,
    whatsapp_status         TEXT NOT NULL DEFAULT 'no_conectado',
    onboarding_done         {t["boolean"]} NOT NULL DEFAULT FALSE,
    plan                    TEXT NOT NULL DEFAULT 'trial',
    subscription_status     TEXT NOT NULL DEFAULT 'trial',
    trial_ends_at           {t["timestamp"]},
    stripe_customer_id      TEXT,
    stripe_subscription_id  TEXT,
    whatsapp_phone_norm     TEXT,
    team_size               TEXT,
    province                TEXT,
    primary_goal            TEXT,
    invoice_template        TEXT NOT NULL DEFAULT 'clasica',
    brand_color             TEXT,
    logo_data               TEXT,
    logo_mime               TEXT,
    created_at              {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id              {t["id"]},
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    business_id     {t["ref"]} NOT NULL REFERENCES businesses(id),
    is_admin        {t["boolean"]} NOT NULL DEFAULT FALSE,
    session_version INTEGER NOT NULL DEFAULT 0,
    created_at      {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    phone       TEXT,
    address     TEXT,
    zone        TEXT,
    nif         TEXT,
    email       TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id              {t["id"]},
    business_id     {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id       {t["ref"]},
    description     TEXT NOT NULL,
    scheduled_for   {t["timestamp"]},
    zone            TEXT,
    price_estimate  {t["real"]},
    status          TEXT NOT NULL DEFAULT 'pendiente',
    created_at      {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id                  {t["id"]},
    business_id         {t["ref"]} NOT NULL REFERENCES businesses(id),
    number              TEXT,
    client_id           {t["ref"]},
    concept             TEXT NOT NULL,
    base                {t["real"]} NOT NULL,
    vat_rate            {t["real"]} NOT NULL,
    vat_amount          {t["real"]} NOT NULL,
    irpf_rate           {t["real"]} NOT NULL DEFAULT 0,
    irpf_amount         {t["real"]} NOT NULL DEFAULT 0,
    total               {t["real"]} NOT NULL,
    status              TEXT NOT NULL DEFAULT 'borrador',
    due_date            {t["timestamp"]},
    issued_at           {t["timestamp"]},
    paid_at             {t["timestamp"]},
    last_reminder_at    {t["timestamp"]},
    reminders_sent      INTEGER NOT NULL DEFAULT 0,
    issuer_name         TEXT,
    issuer_nif          TEXT,
    issuer_address      TEXT,
    recipient_name      TEXT,
    recipient_nif       TEXT,
    recipient_address   TEXT,
    created_at          {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS expenses (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    concept     TEXT NOT NULL,
    amount      {t["real"]} NOT NULL,
    vat_rate    {t["real"]},
    category    TEXT,
    spent_on    {t["timestamp"]},
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    number      TEXT,
    client_id   {t["ref"]},
    concept     TEXT NOT NULL,
    base        {t["real"]} NOT NULL,
    vat_rate    {t["real"]} NOT NULL,
    vat_amount  {t["real"]} NOT NULL,
    irpf_rate   {t["real"]} NOT NULL DEFAULT 0,
    irpf_amount {t["real"]} NOT NULL DEFAULT 0,
    total       {t["real"]} NOT NULL,
    status      TEXT NOT NULL DEFAULT 'borrador',
    valid_until {t["timestamp"]},
    invoice_id  {t["ref"]},
    created_at  {t["timestamp"]} NOT NULL,
    accepted_at {t["timestamp"]},
    UNIQUE (business_id, id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);

CREATE TABLE IF NOT EXISTS password_resets (
    id          {t["id"]},
    user_id     {t["ref"]} NOT NULL REFERENCES users(id),
    token_hash  TEXT NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    used        {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS document_sequences (
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    kind        TEXT NOT NULL,
    year        INTEGER NOT NULL,
    last_number INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (business_id, kind, year)
);

CREATE TABLE IF NOT EXISTS webhook_events (
    source      TEXT NOT NULL,
    event_id    TEXT NOT NULL,
    created_at  {t["timestamp"]} NOT NULL,
    PRIMARY KEY (source, event_id)
);

CREATE TABLE IF NOT EXISTS product_events (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    event_name  TEXT NOT NULL,
    event_data  TEXT,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS whatsapp_links (
    code_hash    TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    expires_at  {t["timestamp"]} NOT NULL,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS scheduled_job_runs (
    run_key     TEXT PRIMARY KEY,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_tokens (
    token       TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id   {t["ref"]} NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    revoked     {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS copilot_recommendations (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    topic       TEXT NOT NULL,
    summary     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'recomendado',
    created_at  {t["timestamp"]} NOT NULL,
    updated_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id   {t["ref"]},
    invoice_id  {t["ref"]},
    kind        TEXT NOT NULL DEFAULT 'documento',
    filename    TEXT NOT NULL,
    stored_name TEXT NOT NULL,
    mime        TEXT,
    size        INTEGER NOT NULL DEFAULT 0,
    ocr_text    TEXT,
    ocr_amount  {t["real"]},
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);
"""


LEGACY_COLUMNS = {
    "businesses": {
        "plan": "TEXT NOT NULL DEFAULT 'trial'",
        "subscription_status": "TEXT NOT NULL DEFAULT 'trial'",
        "trial_ends_at": "TEXT",
        "stripe_customer_id": "TEXT",
        "stripe_subscription_id": "TEXT",
        "whatsapp_phone_norm": "TEXT",
        "team_size": "TEXT",
        "province": "TEXT",
        "primary_goal": "TEXT",
        "invoice_template": "TEXT NOT NULL DEFAULT 'clasica'",
        "brand_color": "TEXT",
        "logo_data": "TEXT",
        "logo_mime": "TEXT",
        "panel_layout": "TEXT",
        "clockin_policy": "TEXT",
        "verifactu_enabled": "BOOLEAN NOT NULL DEFAULT FALSE",
        "payment_iban": "TEXT",
        "payment_bizum": "TEXT",
        "payment_note": "TEXT",
    },
    "users": {
        "is_admin": "INTEGER NOT NULL DEFAULT 0",
        "session_version": "INTEGER NOT NULL DEFAULT 0",
    },
    "clients": {"nif": "TEXT", "email": "TEXT"},
    "jobs": {"worker_id": "INTEGER"},
    "invoices": {
        "last_reminder_at": "TEXT",
        "reminders_sent": "INTEGER NOT NULL DEFAULT 0",
        "issuer_name": "TEXT",
        "issuer_nif": "TEXT",
        "issuer_address": "TEXT",
        "recipient_name": "TEXT",
        "recipient_nif": "TEXT",
        "recipient_address": "TEXT",
    },
}


def _column_names(conn, table: str) -> set[str]:
    if conn.dialect == "sqlite":
        return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}
    rows = conn.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema=current_schema() AND table_name=?",
        (table,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _upgrade_initial(conn) -> None:
    conn.executescript(_initial_schema(conn.dialect))
    # Adopta instalaciones SQLite anteriores sin volver a ALTERar en cada arranque.
    if conn.dialect == "sqlite":
        for table, columns in LEGACY_COLUMNS.items():
            present = _column_names(conn, table)
            for column, declaration in columns.items():
                if column not in present:
                    conn.execute(
                        f"ALTER TABLE {table} ADD COLUMN {column} {declaration}"
                    )


def _downgrade_initial(conn) -> None:
    for table in (
        "documents", "copilot_recommendations", "portal_tokens",
        "scheduled_job_runs", "whatsapp_links", "product_events",
        "webhook_events", "document_sequences", "password_resets", "quotes",
        "expenses", "invoices", "jobs", "clients", "users", "businesses",
    ):
        conn.execute(f"DROP TABLE IF EXISTS {table}")


INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_clients_business ON clients(business_id)",
    "CREATE INDEX IF NOT EXISTS idx_jobs_business_date ON jobs(business_id, scheduled_for)",
    "CREATE INDEX IF NOT EXISTS idx_invoices_business_status ON invoices(business_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_expenses_business_date ON expenses(business_id, spent_on)",
    "CREATE INDEX IF NOT EXISTS idx_quotes_business_status ON quotes(business_id, status)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_invoice_number "
    "ON invoices(business_id, number) WHERE number IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_quote_number "
    "ON quotes(business_id, number) WHERE number IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_whatsapp_phone "
    "ON businesses(whatsapp_phone_norm) WHERE whatsapp_phone_norm IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_clients_business_id ON clients(business_id, id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_invoices_business_id ON invoices(business_id, id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_jobs_business_id ON jobs(business_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_portal_tokens_client ON portal_tokens(business_id, client_id)",
    "CREATE INDEX IF NOT EXISTS idx_copilot_recs_business "
    "ON copilot_recommendations(business_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_product_events_business_date "
    "ON product_events(business_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_product_events_name_date "
    "ON product_events(event_name, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_documents_business ON documents(business_id)",
    "CREATE INDEX IF NOT EXISTS idx_documents_client ON documents(business_id, client_id)",
    "CREATE INDEX IF NOT EXISTS idx_workers_business ON workers(business_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_workers_business_phone "
    "ON workers(business_id, phone_norm) WHERE phone_norm IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_jobs_worker ON jobs(business_id, worker_id)",
    "CREATE INDEX IF NOT EXISTS idx_clockins_worker "
    "ON worker_clockins(business_id, worker_id, at)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_clockins_business_id "
    "ON worker_clockins(business_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_clockin_corrections_clockin "
    "ON worker_clockin_corrections(business_id, clockin_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_invoice_records_issuer "
    "ON invoice_records(business_id, issuer_nif, id)",
    "CREATE INDEX IF NOT EXISTS idx_invoice_events_business "
    "ON invoice_events(business_id, created_at, id)",
)


SQLITE_TENANT_RELATIONS = (
    ("jobs", "client_id", "clients"),
    ("jobs", "worker_id", "workers"),
    ("invoices", "client_id", "clients"),
    ("quotes", "client_id", "clients"),
    ("quotes", "invoice_id", "invoices"),
    ("documents", "client_id", "clients"),
    ("documents", "invoice_id", "invoices"),
    ("portal_tokens", "client_id", "clients"),
)


def _index_targets_exist(conn, statement: str) -> bool:
    target = statement.split(" ON ", 1)[1]
    table = target.split("(", 1)[0].strip()
    if not _table_exists(conn, table):
        return False
    columns = target.split("(", 1)[1].split(")", 1)[0].split(",")
    existing = _column_names(conn, table)
    return all(column.strip() in existing for column in columns)


def _sqlite_tenant_trigger(table: str, column: str, parent: str, event: str) -> str:
    name = f"{table}_{column}_same_business_{event.lower()}"
    timing = (
        f"BEFORE INSERT ON {table}"
        if event == "INSERT"
        else f"BEFORE UPDATE OF business_id, {column} ON {table}"
    )
    return f"""
CREATE TRIGGER IF NOT EXISTS {name}
{timing}
WHEN NEW.{column} IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM {parent}
    WHERE id=NEW.{column} AND business_id=NEW.business_id
)
BEGIN
    SELECT RAISE(ABORT, '{column} pertenece a otro negocio');
END;
"""


def _upgrade_tenant_integrity(conn) -> None:
    for statement in INDEXES:
        if _index_targets_exist(conn, statement):
            conn.execute(statement)
    # Las instalaciones SQLite heredadas no pueden añadir FKs con ALTER TABLE.
    # Estos triggers aplican la misma restricción a sus relaciones multiempresa.
    if conn.dialect == "sqlite":
        for table, column, parent in SQLITE_TENANT_RELATIONS:
            if not _table_exists(conn, table) or not _table_exists(conn, parent):
                continue
            for event in ("INSERT", "UPDATE"):
                conn.executescript(
                    _sqlite_tenant_trigger(table, column, parent, event)
                )


def _downgrade_tenant_integrity(conn) -> None:
    if conn.dialect == "sqlite":
        for table, column, _parent in SQLITE_TENANT_RELATIONS:
            conn.execute(
                f"DROP TRIGGER IF EXISTS "
                f"{table}_{column}_same_business_insert"
            )
            conn.execute(
                f"DROP TRIGGER IF EXISTS "
                f"{table}_{column}_same_business_update"
            )
    for statement in reversed(INDEXES):
        name = statement.split("INDEX IF NOT EXISTS ", 1)[1].split(" ", 1)[0]
        conn.execute(f"DROP INDEX IF EXISTS {name}")


def _upgrade_whatsapp_outbox(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS whatsapp_outbox (
    id                  {t["id"]},
    business_id         {t["ref"]} REFERENCES businesses(id),
    to_phone            TEXT NOT NULL,
    message_type        TEXT NOT NULL,
    text_body           TEXT,
    template_name       TEXT,
    template_language   TEXT,
    template_params     TEXT,
    idempotency_key     TEXT UNIQUE,
    status              TEXT NOT NULL DEFAULT 'queued',
    attempts            INTEGER NOT NULL DEFAULT 0,
    max_attempts        INTEGER NOT NULL DEFAULT 5,
    next_attempt_at     {t["timestamp"]} NOT NULL,
    locked_at           {t["timestamp"]},
    meta_message_id     TEXT UNIQUE,
    last_error          TEXT,
    sent_at             {t["timestamp"]},
    delivered_at        {t["timestamp"]},
    read_at             {t["timestamp"]},
    created_at          {t["timestamp"]} NOT NULL,
    updated_at          {t["timestamp"]} NOT NULL,
    CHECK (message_type IN ('text', 'template')),
    CHECK (status IN ('queued', 'processing', 'retrying', 'sent',
                      'delivered', 'read', 'failed'))
);
"""
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_due "
        "ON whatsapp_outbox(status, next_attempt_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_business "
        "ON whatsapp_outbox(business_id, created_at)"
    )


def _downgrade_whatsapp_outbox(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_whatsapp_outbox_business")
    conn.execute("DROP INDEX IF EXISTS idx_whatsapp_outbox_due")
    conn.execute("DROP TABLE IF EXISTS whatsapp_outbox")


def _upgrade_panel_layout(conn) -> None:
    # Guarda cómo cada negocio ordena/oculta los bloques de su panel de inicio.
    if "panel_layout" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN panel_layout TEXT")


def _downgrade_panel_layout(conn) -> None:
    # SQLite no soporta DROP COLUMN en versiones antiguas; se deja la columna
    # (es nullable y opcional, no rompe nada al revertir).
    if conn.dialect != "sqlite":
        conn.execute("ALTER TABLE businesses DROP COLUMN IF EXISTS panel_layout")


def _table_exists(conn, table: str) -> bool:
    if conn.dialect == "sqlite":
        row = conn.execute(
            "SELECT 1 AS found FROM sqlite_master "
            "WHERE type='table' AND name=?",
            (table,),
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT 1 AS found FROM information_schema.tables "
            "WHERE table_schema=current_schema() AND table_name=?",
            (table,),
        ).fetchone()
    return bool(row)


def _postgres_constraint_exists(conn, name: str) -> bool:
    if conn.dialect != "postgres":
        return False
    row = conn.execute(
        "SELECT 1 AS found FROM pg_constraint c "
        "JOIN pg_namespace n ON n.oid=c.connamespace "
        "WHERE n.nspname=current_schema() AND c.conname=?",
        (name,),
    ).fetchone()
    return bool(row)


def _upgrade_team_clockins(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS workers (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    phone       TEXT,
    phone_norm  TEXT,
    color       TEXT,
    access_code TEXT NOT NULL,
    pin_hash    TEXT,
    active      {t["boolean"]} NOT NULL DEFAULT TRUE,
    created_at  {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id),
    UNIQUE (business_id, access_code)
);
"""
    )
    if "worker_id" not in _column_names(conn, "jobs"):
        conn.execute(f"ALTER TABLE jobs ADD COLUMN worker_id {t['ref']}")

    # La FK compuesta de fichajes necesita una clave única por negocio en jobs.
    for statement in INDEXES:
        if _index_targets_exist(conn, statement):
            conn.execute(statement)

    if conn.dialect == "postgres" and not _postgres_constraint_exists(
        conn, "jobs_worker_same_business"
    ):
        conn.execute(
            "ALTER TABLE jobs ADD CONSTRAINT jobs_worker_same_business "
            "FOREIGN KEY (business_id, worker_id) "
            "REFERENCES workers(business_id, id)"
        )

    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS worker_clockins (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    worker_id   {t["ref"]} NOT NULL,
    job_id      {t["ref"]},
    action      TEXT NOT NULL CHECK (action IN ('entrada', 'salida')),
    at          {t["timestamp"]} NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('web', 'whatsapp')),
    lat         {t["real"]},
    lng         {t["real"]},
    accuracy    {t["real"]},
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id),
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id)
);

CREATE TABLE IF NOT EXISTS worker_tokens (
    token       TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    worker_id   {t["ref"]} NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    revoked     {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id)
);
"""
    )
    for statement in INDEXES:
        if _index_targets_exist(conn, statement):
            conn.execute(statement)

    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger("jobs", "worker_id", "workers", event)
            )


def _downgrade_team_clockins(conn) -> None:
    if conn.dialect == "sqlite":
        conn.execute("UPDATE jobs SET worker_id=NULL")
        conn.execute("DROP TRIGGER IF EXISTS jobs_worker_id_same_business_insert")
        conn.execute("DROP TRIGGER IF EXISTS jobs_worker_id_same_business_update")
    else:
        conn.execute(
            "ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_worker_same_business"
        )
    for name in (
        "idx_clockins_worker", "idx_jobs_worker", "idx_workers_business",
    ):
        conn.execute(f"DROP INDEX IF EXISTS {name}")
    conn.execute("DROP TABLE IF EXISTS worker_tokens")
    conn.execute("DROP TABLE IF EXISTS worker_clockins")
    conn.execute("DROP TABLE IF EXISTS workers")
    if conn.dialect != "sqlite":
        conn.execute("ALTER TABLE jobs DROP COLUMN IF EXISTS worker_id")


def _sqlite_rebuild_clockins_v6(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE worker_clockins_v6 (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    worker_id   {t["ref"]} NOT NULL,
    job_id      {t["ref"]},
    action      TEXT NOT NULL
                CHECK (action IN ('entrada', 'salida', 'pausa', 'reanudar')),
    at          {t["timestamp"]} NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('web', 'whatsapp')),
    lat         {t["real"]},
    lng         {t["real"]},
    accuracy    {t["real"]},
    created_at  {t["timestamp"]} NOT NULL,
    seal        TEXT,
    prev_seal   TEXT,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id),
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id)
);
INSERT INTO worker_clockins_v6
    (id, business_id, worker_id, job_id, action, at, source, lat, lng,
     accuracy, created_at)
SELECT id, business_id, worker_id, job_id, action, at, source, lat, lng,
       accuracy, created_at
FROM worker_clockins;
DROP TABLE worker_clockins;
ALTER TABLE worker_clockins_v6 RENAME TO worker_clockins;
"""
    )


def _backfill_clockin_seals(conn) -> None:
    rows = conn.execute(
        "SELECT * FROM worker_clockins "
        "ORDER BY business_id, worker_id, id"
    ).fetchall()
    previous: dict[tuple[int, int], str | None] = {}
    for row in rows:
        key = (int(row["business_id"]), int(row["worker_id"]))
        prev_seal = previous.get(key)
        seal = clockin_seal(row, prev_seal)
        conn.execute(
            "UPDATE worker_clockins SET prev_seal=?, seal=? "
            "WHERE id=? AND business_id=?",
            (prev_seal, seal, row["id"], row["business_id"]),
        )
        previous[key] = seal


def _install_clockin_append_only(conn) -> None:
    if conn.dialect == "sqlite":
        conn.executescript(
            """
CREATE TRIGGER IF NOT EXISTS worker_clockins_require_seal
BEFORE INSERT ON worker_clockins
WHEN NEW.seal IS NULL OR NEW.seal=''
BEGIN
    SELECT RAISE(ABORT, 'todo fichaje necesita sello');
END;
CREATE TRIGGER IF NOT EXISTS worker_clockins_append_only_update
BEFORE UPDATE ON worker_clockins
BEGIN
    SELECT RAISE(ABORT, 'los fichajes son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS worker_clockins_append_only_delete
BEFORE DELETE ON worker_clockins
BEGIN
    SELECT RAISE(ABORT, 'los fichajes son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS clockin_corrections_append_only_update
BEFORE UPDATE ON worker_clockin_corrections
BEGIN
    SELECT RAISE(ABORT, 'las correcciones son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS clockin_corrections_append_only_delete
BEFORE DELETE ON worker_clockin_corrections
BEGIN
    SELECT RAISE(ABORT, 'las correcciones son inalterables');
END;
"""
        )
        return
    conn.execute(
        """
CREATE OR REPLACE FUNCTION noesis_clockins_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'los registros de jornada son inalterables';
END;
$$ LANGUAGE plpgsql
"""
    )
    for table in ("worker_clockins", "worker_clockin_corrections"):
        trigger = f"{table}_append_only"
        conn.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        conn.execute(
            f"CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION noesis_clockins_append_only()"
        )


def _upgrade_immutable_clockins(conn) -> None:
    t = _types(conn.dialect)
    if "clockin_policy" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN clockin_policy TEXT")

    columns = _column_names(conn, "worker_clockins")
    if conn.dialect == "sqlite" and "seal" not in columns:
        _sqlite_rebuild_clockins_v6(conn)
    elif conn.dialect == "postgres":
        if "seal" not in columns:
            conn.execute("ALTER TABLE worker_clockins ADD COLUMN seal TEXT")
        if "prev_seal" not in columns:
            conn.execute("ALTER TABLE worker_clockins ADD COLUMN prev_seal TEXT")
        conn.execute(
            "ALTER TABLE worker_clockins "
            "DROP CONSTRAINT IF EXISTS worker_clockins_action_check"
        )
        conn.execute(
            "ALTER TABLE worker_clockins ADD CONSTRAINT "
            "worker_clockins_action_check CHECK "
            "(action IN ('entrada', 'salida', 'pausa', 'reanudar'))"
        )

    _backfill_clockin_seals(conn)
    if conn.dialect == "postgres":
        conn.execute("ALTER TABLE worker_clockins ALTER COLUMN seal SET NOT NULL")

    for statement in INDEXES:
        if _index_targets_exist(conn, statement):
            conn.execute(statement)

    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS worker_clockin_corrections (
    id             {t["id"]},
    business_id    {t["ref"]} NOT NULL REFERENCES businesses(id),
    clockin_id     {t["ref"]} NOT NULL,
    author_user_id {t["ref"]} NOT NULL REFERENCES users(id),
    reason         TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'corregido'
                   CHECK (status IN ('corregido', 'anulado')),
    old_at         {t["timestamp"]},
    new_at         {t["timestamp"]},
    created_at     {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, clockin_id)
        REFERENCES worker_clockins(business_id, id)
);
"""
    )
    for statement in INDEXES:
        if _index_targets_exist(conn, statement):
            conn.execute(statement)
    _install_clockin_append_only(conn)


def _downgrade_immutable_clockins(conn) -> None:
    if conn.dialect == "sqlite":
        for trigger in (
            "worker_clockins_require_seal",
            "worker_clockins_append_only_update",
            "worker_clockins_append_only_delete",
            "clockin_corrections_append_only_update",
            "clockin_corrections_append_only_delete",
        ):
            conn.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    else:
        for table in ("worker_clockins", "worker_clockin_corrections"):
            conn.execute(
                f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}"
            )
        conn.execute("DROP FUNCTION IF EXISTS noesis_clockins_append_only()")
    conn.execute("DROP INDEX IF EXISTS idx_clockin_corrections_clockin")
    conn.execute("DROP TABLE IF EXISTS worker_clockin_corrections")
    # Las columnas y el CHECK ampliado se conservan: eliminarlos podría destruir
    # sellos o hacer imposible revertir si ya existen pausas.


def _install_invoice_append_only(conn) -> None:
    tables = ("invoice_records", "invoice_events")
    if conn.dialect == "sqlite":
        for table in tables:
            conn.executescript(
                f"""
CREATE TRIGGER IF NOT EXISTS {table}_append_only_update
BEFORE UPDATE ON {table}
BEGIN
    SELECT RAISE(ABORT, 'los registros VeriFactu son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS {table}_append_only_delete
BEFORE DELETE ON {table}
BEGIN
    SELECT RAISE(ABORT, 'los registros VeriFactu son inalterables');
END;
"""
            )
        conn.executescript(
            """
CREATE TRIGGER IF NOT EXISTS invoice_records_require_hash
BEFORE INSERT ON invoice_records
WHEN NEW.record_hash IS NULL OR NEW.record_hash=''
BEGIN
    SELECT RAISE(ABORT, 'todo registro VeriFactu necesita huella');
END;
"""
        )
        return
    conn.execute(
        """
CREATE OR REPLACE FUNCTION noesis_invoice_records_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'los registros VeriFactu son inalterables';
END;
$$ LANGUAGE plpgsql
"""
    )
    for table in tables:
        trigger = f"{table}_append_only"
        conn.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        conn.execute(
            f"CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION noesis_invoice_records_append_only()"
        )


def _upgrade_verifactu_phase1(conn) -> None:
    t = _types(conn.dialect)
    business_columns = _column_names(conn, "businesses")
    if "verifactu_enabled" not in business_columns:
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN "
            f"verifactu_enabled {t['boolean']} NOT NULL DEFAULT FALSE"
        )

    invoice_columns = _column_names(conn, "invoices")
    additions = (
        ("invoice_type", "TEXT NOT NULL DEFAULT 'F1'"),
        ("rectifies_invoice_id", t["ref"]),
        ("rectification_type", "TEXT"),
        ("rectification_reason", "TEXT"),
    )
    for column, definition in additions:
        if column not in invoice_columns:
            conn.execute(
                f"ALTER TABLE invoices ADD COLUMN {column} {definition}"
            )

    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS invoice_records (
    id                       {t["id"]},
    business_id              {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id               {t["ref"]} NOT NULL,
    record_type              TEXT NOT NULL DEFAULT 'alta'
                             CHECK (record_type IN ('alta')),
    record_version           TEXT NOT NULL,
    invoice_type             TEXT NOT NULL,
    rectification_type       TEXT,
    rectified_issuer_nif     TEXT,
    rectified_invoice_number TEXT,
    rectified_issue_date     TEXT,
    issuer_nif               TEXT NOT NULL,
    issuer_name              TEXT NOT NULL,
    invoice_number           TEXT NOT NULL,
    issue_date               TEXT NOT NULL,
    recipient_nif            TEXT NOT NULL,
    recipient_name           TEXT NOT NULL,
    description              TEXT NOT NULL,
    breakdown_json           TEXT NOT NULL,
    vat_total                {t["real"]} NOT NULL,
    invoice_total            {t["real"]} NOT NULL,
    generated_at             TEXT NOT NULL,
    previous_record_id       {t["ref"]},
    previous_issuer_nif      TEXT,
    previous_invoice_number  TEXT,
    previous_issue_date      TEXT,
    previous_hash            TEXT,
    hash_algorithm           TEXT NOT NULL,
    hash_type                TEXT NOT NULL,
    hash_spec_version        TEXT NOT NULL,
    record_hash              TEXT NOT NULL,
    qr_url                   TEXT NOT NULL,
    producer_name            TEXT NOT NULL,
    producer_nif             TEXT NOT NULL,
    system_name              TEXT NOT NULL,
    system_id                TEXT NOT NULL,
    system_version           TEXT NOT NULL,
    installation_id          TEXT NOT NULL,
    created_at               TEXT NOT NULL,
    UNIQUE (business_id, id),
    UNIQUE (business_id, invoice_id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, previous_record_id)
        REFERENCES invoice_records(business_id, id)
);

CREATE TABLE IF NOT EXISTS invoice_events (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id  {t["ref"]},
    record_id   {t["ref"]},
    event_type  TEXT NOT NULL
                CHECK (event_type IN
                    ('alta', 'rectificacion', 'exportacion', 'anomalia')),
    details     TEXT,
    created_at  TEXT NOT NULL,
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, record_id)
        REFERENCES invoice_records(business_id, id)
);
"""
    )
    for statement in INDEXES:
        if _index_targets_exist(conn, statement):
            conn.execute(statement)
    _install_invoice_append_only(conn)


def _downgrade_verifactu_phase1(conn) -> None:
    if conn.dialect == "sqlite":
        for trigger in (
            "invoice_records_append_only_update",
            "invoice_records_append_only_delete",
            "invoice_events_append_only_update",
            "invoice_events_append_only_delete",
            "invoice_records_require_hash",
        ):
            conn.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    else:
        for table in ("invoice_records", "invoice_events"):
            conn.execute(
                f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}"
            )
        conn.execute(
            "DROP FUNCTION IF EXISTS noesis_invoice_records_append_only()"
        )
    conn.execute("DROP INDEX IF EXISTS idx_invoice_events_business")
    conn.execute("DROP INDEX IF EXISTS idx_invoice_records_issuer")
    conn.execute("DROP TABLE IF EXISTS invoice_events")
    conn.execute("DROP TABLE IF EXISTS invoice_records")
    # Las columnas se conservan para no perder la relación de rectificativas ni
    # reactivar accidentalmente un modo que el negocio hubiera desactivado.


def _upgrade_verified_backups(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS backup_runs (
    id          {t["id"]},
    created_at  {t["timestamp"]} NOT NULL,
    filename    TEXT,
    size_bytes  BIGINT NOT NULL DEFAULT 0,
    status      TEXT NOT NULL CHECK (status IN ('ok', 'error')),
    storage     TEXT NOT NULL,
    error       TEXT
);
CREATE INDEX IF NOT EXISTS idx_backup_runs_created
    ON backup_runs(created_at);
"""
    )


def _downgrade_verified_backups(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_backup_runs_created")
    conn.execute("DROP TABLE IF EXISTS backup_runs")


def _expand_invoice_event_types(conn) -> None:
    """Añade eventos de remisión sin alterar nunca los eventos existentes."""
    allowed = (
        "'alta', 'rectificacion', 'exportacion', 'anomalia', "
        "'remision', 'aceptacion', 'rechazo'"
    )
    if conn.dialect == "sqlite":
        conn.execute("DROP TRIGGER IF EXISTS invoice_events_append_only_update")
        conn.execute("DROP TRIGGER IF EXISTS invoice_events_append_only_delete")
        conn.execute("DROP INDEX IF EXISTS idx_invoice_events_business")
        conn.executescript(
            f"""
CREATE TABLE invoice_events_v9 (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL REFERENCES businesses(id),
    invoice_id  INTEGER,
    record_id   INTEGER,
    event_type  TEXT NOT NULL CHECK (event_type IN ({allowed})),
    details     TEXT,
    created_at  TEXT NOT NULL,
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, record_id)
        REFERENCES invoice_records(business_id, id)
);
INSERT INTO invoice_events_v9
    (id, business_id, invoice_id, record_id, event_type, details, created_at)
SELECT id, business_id, invoice_id, record_id, event_type, details, created_at
FROM invoice_events;
DROP TABLE invoice_events;
ALTER TABLE invoice_events_v9 RENAME TO invoice_events;
"""
        )
    else:
        conn.execute(
            "ALTER TABLE invoice_events DROP CONSTRAINT IF EXISTS "
            "invoice_events_event_type_check"
        )
        conn.execute(
            "ALTER TABLE invoice_events ADD CONSTRAINT "
            f"invoice_events_event_type_check CHECK (event_type IN ({allowed}))"
        )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_invoice_events_business "
        "ON invoice_events(business_id, created_at, id)"
    )
    _install_invoice_append_only(conn)


def _upgrade_verifactu_phase2(conn) -> None:
    t = _types(conn.dialect)
    _expand_invoice_event_types(conn)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS verifactu_outbox (
    id                    {t["id"]},
    business_id           {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id            {t["ref"]} NOT NULL,
    record_id             {t["ref"]} NOT NULL,
    status                TEXT NOT NULL DEFAULT 'pendiente'
                          CHECK (status IN (
                              'pendiente', 'enviado', 'aceptado',
                              'aceptado_con_errores', 'rechazado'
                          )),
    attempts              INTEGER NOT NULL DEFAULT 0,
    max_attempts          INTEGER NOT NULL DEFAULT 6,
    next_attempt_at       {t["timestamp"]} NOT NULL,
    locked_at             {t["timestamp"]},
    sent_at               {t["timestamp"]},
    completed_at          {t["timestamp"]},
    aeat_csv              TEXT,
    aeat_global_status    TEXT,
    aeat_error_code       TEXT,
    aeat_error_description TEXT,
    aeat_response         TEXT,
    wait_seconds          INTEGER NOT NULL DEFAULT 0,
    last_error            TEXT,
    created_at            {t["timestamp"]} NOT NULL,
    updated_at            {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, record_id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, record_id)
        REFERENCES invoice_records(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_verifactu_outbox_due
    ON verifactu_outbox(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_verifactu_outbox_business
    ON verifactu_outbox(business_id, invoice_id, id);
"""
    )


def _downgrade_verifactu_phase2(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_verifactu_outbox_business")
    conn.execute("DROP INDEX IF EXISTS idx_verifactu_outbox_due")
    conn.execute("DROP TABLE IF EXISTS verifactu_outbox")
    # Los nuevos eventos se conservan: estrechar el CHECK podría destruir auditoría.


def _upgrade_payment_details(conn) -> None:
    """Datos de cobro del negocio (IBAN/Bizum/nota) para el PDF y el portal."""
    cols = _column_names(conn, "businesses")
    for col in ("payment_iban", "payment_bizum", "payment_note"):
        if col not in cols:
            conn.execute(f"ALTER TABLE businesses ADD COLUMN {col} TEXT")


def _downgrade_payment_details(conn) -> None:
    if conn.dialect == "postgres":
        for col in ("payment_iban", "payment_bizum", "payment_note"):
            conn.execute(f"ALTER TABLE businesses DROP COLUMN IF EXISTS {col}")
    # En SQLite se conservan las columnas (DROP COLUMN es frágil); no molestan.


def _upgrade_partial_payments(conn) -> None:
    """Ledger de cobros separado de los registros fiscales inmutables."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS invoice_payments (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id  {t["ref"]} NOT NULL,
    amount      {t["real"]} NOT NULL CHECK (amount > 0),
    method      TEXT,
    paid_at     {t["timestamp"]} NOT NULL,
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_invoice_payments_invoice
    ON invoice_payments(business_id, invoice_id, paid_at, id);
"""
    )
    # Las facturas cobradas antes de esta migración entran en el ledger para que
    # este sea la única fuente de verdad desde ahora.
    conn.execute(
        "INSERT INTO invoice_payments "
        "(business_id, invoice_id, amount, method, paid_at, note, created_at) "
        "SELECT i.business_id, i.id, i.total, 'registro_anterior', "
        "COALESCE(i.paid_at, i.issued_at, i.created_at), "
        "'Cobro migrado desde el estado anterior', "
        "COALESCE(i.paid_at, i.issued_at, i.created_at) "
        "FROM invoices i WHERE i.status='cobrada' AND i.total > 0 "
        "AND NOT EXISTS (SELECT 1 FROM invoice_payments p "
        "WHERE p.business_id=i.business_id AND p.invoice_id=i.id)"
    )


def _downgrade_partial_payments(conn) -> None:
    # Sin ledger no se puede representar un cobro parcial.
    conn.execute("UPDATE invoices SET status='enviada' WHERE status='parcial'")
    conn.execute("DROP INDEX IF EXISTS idx_invoice_payments_invoice")
    conn.execute("DROP TABLE IF EXISTS invoice_payments")


def _upgrade_expense_from_photo(conn) -> None:
    """Relaciona el documento original con el gasto confirmado por el usuario."""
    t = _types(conn.dialect)
    if "expense_id" not in _column_names(conn, "documents"):
        conn.execute(
            f"ALTER TABLE documents ADD COLUMN expense_id {t['ref']}"
        )
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_expenses_business_id "
        "ON expenses(business_id, id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_documents_expense "
        "ON documents(business_id, expense_id)"
    )
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE documents ADD CONSTRAINT "
            "documents_business_expense_fk "
            "FOREIGN KEY (business_id, expense_id) "
            "REFERENCES expenses(business_id, id)"
        )
    else:
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger(
                    "documents", "expense_id", "expenses", event
                )
            )


def _downgrade_expense_from_photo(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE documents DROP CONSTRAINT IF EXISTS "
            "documents_business_expense_fk"
        )
        conn.execute(
            "ALTER TABLE documents DROP COLUMN IF EXISTS expense_id"
        )
    else:
        for event in ("insert", "update"):
            conn.execute(
                "DROP TRIGGER IF EXISTS "
                f"documents_expense_id_same_business_{event}"
            )
    conn.execute("DROP INDEX IF EXISTS idx_documents_expense")
    conn.execute("DROP INDEX IF EXISTS uq_expenses_business_id")


def _upgrade_payment_reminders(conn) -> None:
    """Preferencias del negocio para reclamar cobros por WhatsApp."""
    t = _types(conn.dialect)
    columns = _column_names(conn, "businesses")
    if "payment_reminders_enabled" not in columns:
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN payment_reminders_enabled "
            f"{t['boolean']} NOT NULL DEFAULT FALSE"
        )
    if "payment_reminder_days" not in columns:
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN payment_reminder_days "
            "TEXT NOT NULL DEFAULT '3,7,15'"
        )


def _downgrade_payment_reminders(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE businesses DROP COLUMN IF EXISTS "
            "payment_reminders_enabled"
        )
        conn.execute(
            "ALTER TABLE businesses DROP COLUMN IF EXISTS payment_reminder_days"
        )
    # SQLite conserva las columnas opcionales para evitar reconstruir businesses.


def _upgrade_whatsapp_brain(conn) -> None:
    """Confirmaciones de mèdia entrante y preferencias de informes por WhatsApp."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS whatsapp_pending_actions (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    phone       TEXT NOT NULL,
    kind        TEXT NOT NULL,
    payload     TEXT NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    created_at  {t["timestamp"]} NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_wa_pending_phone
    ON whatsapp_pending_actions(business_id, phone);
"""
    )
    if "whatsapp_reports" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN whatsapp_reports TEXT")


def _downgrade_whatsapp_brain(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS uq_wa_pending_phone")
    conn.execute("DROP TABLE IF EXISTS whatsapp_pending_actions")
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE businesses DROP COLUMN IF EXISTS whatsapp_reports"
        )
    # SQLite conserva la columna opcional para evitar reconstruir businesses.


def _upgrade_gestoria(conn) -> None:
    """Datos de la gestoría del negocio y token del portal de descarga."""
    columns = _column_names(conn, "businesses")
    for column, ddl in (
        ("gestoria_name", "TEXT"),
        ("gestoria_email", "TEXT"),
        ("gestoria_cadence", "TEXT NOT NULL DEFAULT 'off'"),
        ("gestoria_token", "TEXT"),
    ):
        if column not in columns:
            conn.execute(f"ALTER TABLE businesses ADD COLUMN {column} {ddl}")
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_businesses_gestoria_token "
        "ON businesses(gestoria_token)"
    )


def _downgrade_gestoria(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS uq_businesses_gestoria_token")
    if conn.dialect == "postgres":
        for column in ("gestoria_name", "gestoria_email", "gestoria_cadence",
                       "gestoria_token"):
            conn.execute(
                f"ALTER TABLE businesses DROP COLUMN IF EXISTS {column}"
            )
    # SQLite conserva las columnas opcionales para evitar reconstruir businesses.


def _upgrade_webhook_lifecycle(conn) -> None:
    """Distingue eventos reservados, completados y fallidos para poder reintentarlos."""
    columns = _column_names(conn, "webhook_events")
    additions = (
        ("status", "TEXT NOT NULL DEFAULT 'done'"),
        ("locked_at", "TEXT"),
        ("processed_at", "TEXT"),
        ("attempts", "INTEGER NOT NULL DEFAULT 1"),
        ("last_error", "TEXT"),
    )
    for column, definition in additions:
        if column not in columns:
            conn.execute(
                f"ALTER TABLE webhook_events ADD COLUMN {column} {definition}"
            )


def _downgrade_webhook_lifecycle(conn) -> None:
    if conn.dialect == "postgres":
        for column in (
            "last_error", "attempts", "processed_at", "locked_at", "status"
        ):
            conn.execute(
                f"ALTER TABLE webhook_events DROP COLUMN IF EXISTS {column}"
            )
    # SQLite conserva columnas opcionales para evitar reconstruir la tabla.


def _upgrade_received_invoices(conn) -> None:
    """Proveedores y facturas recibidas, con estados de revisión en documentos.

    El documento apunta a la recibida confirmada (mismo patrón que expense_id):
    la extracción por IA solo produce borradores; el registro nace al confirmar.
    """
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS suppliers (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    nif         TEXT,
    email       TEXT,
    phone       TEXT,
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_suppliers_business ON suppliers(business_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_suppliers_business_id
    ON suppliers(business_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_suppliers_business_name
    ON suppliers(business_id, name);

CREATE TABLE IF NOT EXISTS received_invoices (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    supplier_id {t["ref"]},
    number      TEXT,
    concept     TEXT,
    issued_on   TEXT,
    due_on      TEXT,
    base        {t["real"]},
    vat_rate    {t["real"]},
    vat_amount  {t["real"]},
    irpf_amount {t["real"]},
    total       {t["real"]} NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pendiente',
    category    TEXT,
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, supplier_id)
        REFERENCES suppliers(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_received_business
    ON received_invoices(business_id);
CREATE INDEX IF NOT EXISTS idx_received_status
    ON received_invoices(business_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_received_business_id
    ON received_invoices(business_id, id);
"""
    )
    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger(
                    "received_invoices", "supplier_id", "suppliers", event
                )
            )

    columns = _column_names(conn, "documents")
    # Los documentos históricos ya estaban gestionados: nacen 'revisado'. Los
    # flujos nuevos de clasificación marcan 'pendiente_revisar' explícitamente.
    additions = (
        ("doc_status", "TEXT NOT NULL DEFAULT 'revisado'"),
        ("confidence", t["real"]),
        ("reviewed_at", t["timestamp"]),
        ("review_note", "TEXT"),
        ("received_invoice_id", t["ref"]),
    )
    for column, definition in additions:
        if column not in columns:
            conn.execute(
                f"ALTER TABLE documents ADD COLUMN {column} {definition}"
            )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_documents_received "
        "ON documents(business_id, received_invoice_id)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_documents_status "
        "ON documents(business_id, doc_status)"
    )
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE documents ADD CONSTRAINT "
            "documents_business_received_fk "
            "FOREIGN KEY (business_id, received_invoice_id) "
            "REFERENCES received_invoices(business_id, id)"
        )
    else:
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger(
                    "documents", "received_invoice_id", "received_invoices",
                    event,
                )
            )


def _downgrade_received_invoices(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE documents DROP CONSTRAINT IF EXISTS "
            "documents_business_received_fk"
        )
        for column in ("received_invoice_id", "review_note", "reviewed_at",
                       "confidence", "doc_status"):
            conn.execute(
                f"ALTER TABLE documents DROP COLUMN IF EXISTS {column}"
            )
    else:
        for event in ("insert", "update"):
            conn.execute(
                "DROP TRIGGER IF EXISTS "
                f"documents_received_invoice_id_same_business_{event}"
            )
            conn.execute(
                "DROP TRIGGER IF EXISTS "
                f"received_invoices_supplier_id_same_business_{event}"
            )
    # SQLite conserva las columnas opcionales para evitar reconstruir documents.
    conn.execute("DROP INDEX IF EXISTS idx_documents_status")
    conn.execute("DROP INDEX IF EXISTS idx_documents_received")
    conn.execute("DROP INDEX IF EXISTS uq_received_business_id")
    conn.execute("DROP INDEX IF EXISTS idx_received_status")
    conn.execute("DROP INDEX IF EXISTS idx_received_business")
    conn.execute("DROP TABLE IF EXISTS received_invoices")
    conn.execute("DROP INDEX IF EXISTS uq_suppliers_business_name")
    conn.execute("DROP INDEX IF EXISTS uq_suppliers_business_id")
    conn.execute("DROP INDEX IF EXISTS idx_suppliers_business")
    conn.execute("DROP TABLE IF EXISTS suppliers")


def _upgrade_platform_base(conn) -> None:
    """Catálogo de productos/servicios, CRM de leads, solicitudes de gestoría
    e idioma preferido del negocio. Todo aislado por business_id."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS products (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'servicio',
    price       {t["real"]} NOT NULL DEFAULT 0,
    cost        {t["real"]},
    vat_rate    {t["real"]},
    unit        TEXT,
    category    TEXT,
    stock       {t["real"]},
    stock_alert {t["real"]},
    active      {t["boolean"]} NOT NULL DEFAULT TRUE,
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_products_business ON products(business_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_products_business_name
    ON products(business_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_products_business_id
    ON products(business_id, id);

CREATE TABLE IF NOT EXISTS leads (
    id             {t["id"]},
    business_id    {t["ref"]} NOT NULL REFERENCES businesses(id),
    name           TEXT NOT NULL,
    phone          TEXT,
    email          TEXT,
    source         TEXT,
    status         TEXT NOT NULL DEFAULT 'nuevo',
    value_estimate {t["real"]},
    note           TEXT,
    next_action_on TEXT,
    client_id      {t["ref"]},
    created_at     {t["timestamp"]} NOT NULL,
    updated_at     {t["timestamp"]},
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_leads_business ON leads(business_id);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(business_id, status);

-- El índice único DEBE existir antes de que gestoria_requests lo referencie:
-- Postgres exige un unique constraint en la columna referida al crear la FK.
CREATE UNIQUE INDEX IF NOT EXISTS uq_documents_business_id
    ON documents(business_id, id);

CREATE TABLE IF NOT EXISTS gestoria_requests (
    id           {t["id"]},
    business_id  {t["ref"]} NOT NULL REFERENCES businesses(id),
    requested_by TEXT NOT NULL DEFAULT 'gestoria',
    message      TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'abierta',
    reply        TEXT,
    document_id  {t["ref"]},
    created_at   {t["timestamp"]} NOT NULL,
    replied_at   {t["timestamp"]},
    FOREIGN KEY (business_id, document_id)
        REFERENCES documents(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_gestoria_requests_business
    ON gestoria_requests(business_id, status);
"""
    )
    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger("leads", "client_id", "clients", event))
            conn.executescript(
                _sqlite_tenant_trigger(
                    "gestoria_requests", "document_id", "documents", event))
    if "language" not in _column_names(conn, "businesses"):
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN language "
            "TEXT NOT NULL DEFAULT 'es'"
        )


def _downgrade_platform_base(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute("ALTER TABLE businesses DROP COLUMN IF EXISTS language")
    else:
        for event in ("insert", "update"):
            conn.execute(
                "DROP TRIGGER IF EXISTS "
                f"leads_client_id_same_business_{event}")
            conn.execute(
                "DROP TRIGGER IF EXISTS "
                f"gestoria_requests_document_id_same_business_{event}")
    # SQLite conserva la columna 'language' para evitar reconstruir businesses.
    conn.execute("DROP INDEX IF EXISTS idx_gestoria_requests_business")
    conn.execute("DROP TABLE IF EXISTS gestoria_requests")
    conn.execute("DROP INDEX IF EXISTS idx_leads_status")
    conn.execute("DROP INDEX IF EXISTS idx_leads_business")
    conn.execute("DROP TABLE IF EXISTS leads")
    conn.execute("DROP INDEX IF EXISTS uq_products_business_id")
    conn.execute("DROP INDEX IF EXISTS uq_products_business_name")
    conn.execute("DROP INDEX IF EXISTS idx_products_business")
    conn.execute("DROP TABLE IF EXISTS products")


def _upgrade_projects(conn) -> None:
    """Proyectos rentables: presupuesto, equipo y costes/hora aislados por negocio."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS projects (
    id            {t["id"]},
    business_id   {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id     {t["ref"]},
    name          TEXT NOT NULL,
    location      TEXT,
    budget        {t["real"]} NOT NULL DEFAULT 0,
    planned_hours {t["real"]} NOT NULL DEFAULT 0,
    progress      INTEGER NOT NULL DEFAULT 0,
    status        TEXT NOT NULL DEFAULT 'planificado',
    starts_on     TEXT,
    ends_on       TEXT,
    note          TEXT,
    created_at    {t["timestamp"]} NOT NULL,
    updated_at    {t["timestamp"]},
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_projects_business_status
    ON projects(business_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_projects_business_id
    ON projects(business_id, id);

CREATE TABLE IF NOT EXISTS project_members (
    business_id {t["ref"]} NOT NULL,
    project_id  {t["ref"]} NOT NULL,
    worker_id   {t["ref"]} NOT NULL,
    role        TEXT,
    hourly_cost {t["real"]} NOT NULL DEFAULT 0,
    created_at  {t["timestamp"]} NOT NULL,
    PRIMARY KEY (business_id, project_id, worker_id),
    FOREIGN KEY (business_id, project_id)
        REFERENCES projects(business_id, id) ON DELETE CASCADE,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id)
);

CREATE TABLE IF NOT EXISTS project_entries (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL,
    project_id  {t["ref"]} NOT NULL,
    worker_id   {t["ref"]},
    kind        TEXT NOT NULL DEFAULT 'otro',
    description TEXT NOT NULL,
    quantity    {t["real"]} NOT NULL DEFAULT 1,
    unit_cost   {t["real"]} NOT NULL DEFAULT 0,
    total       {t["real"]} NOT NULL DEFAULT 0,
    entry_on    TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, project_id)
        REFERENCES projects(business_id, id) ON DELETE CASCADE,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_project_entries_project
    ON project_entries(business_id, project_id, entry_on);
"""
    )
    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger("projects", "client_id", "clients", event)
            )
            conn.executescript(
                _sqlite_tenant_trigger(
                    "project_members", "project_id", "projects", event
                )
            )
            conn.executescript(
                _sqlite_tenant_trigger(
                    "project_members", "worker_id", "workers", event
                )
            )
            conn.executescript(
                _sqlite_tenant_trigger(
                    "project_entries", "project_id", "projects", event
                )
            )
            conn.executescript(
                _sqlite_tenant_trigger(
                    "project_entries", "worker_id", "workers", event
                )
            )


def _downgrade_projects(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_project_entries_project")
    conn.execute("DROP TABLE IF EXISTS project_entries")
    conn.execute("DROP TABLE IF EXISTS project_members")
    conn.execute("DROP INDEX IF EXISTS uq_projects_business_id")
    conn.execute("DROP INDEX IF EXISTS idx_projects_business_status")
    conn.execute("DROP TABLE IF EXISTS projects")


def _upgrade_explanation_level(conn) -> None:
    if "explanation_level" not in _column_names(conn, "businesses"):
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN explanation_level "
            "TEXT NOT NULL DEFAULT 'claro'"
        )


def _downgrade_explanation_level(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE businesses DROP COLUMN IF EXISTS explanation_level"
        )
    # SQLite conserva la columna para evitar reconstruir businesses.


def _upgrade_companion_memory(conn) -> None:
    """Conversación durable, memoria auditable y aprendizaje documental.

    La conversación y las correcciones pertenecen siempre a un negocio. La
    clasificación solo propone; ``confirmed_kind`` deja constancia de la decisión
    humana sin reescribir el intento original.
    """
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS assistant_messages (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    channel     TEXT NOT NULL DEFAULT 'web',
    role        TEXT NOT NULL,
    content     TEXT NOT NULL,
    page        TEXT,
    source      TEXT,
    created_at  {t["timestamp"]} NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_assistant_messages_business
    ON assistant_messages(business_id, created_at, id);

CREATE TABLE IF NOT EXISTS business_memories (
    id             {t["id"]},
    business_id    {t["ref"]} NOT NULL REFERENCES businesses(id),
    scope_type     TEXT NOT NULL DEFAULT 'business',
    scope_id       {t["ref"]} NOT NULL DEFAULT 0,
    memory_key     TEXT NOT NULL,
    memory_value   TEXT NOT NULL,
    source         TEXT NOT NULL DEFAULT 'user',
    confidence     {t["real"]},
    user_confirmed {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at     {t["timestamp"]} NOT NULL,
    updated_at     {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, scope_type, scope_id, memory_key)
);
CREATE INDEX IF NOT EXISTS idx_business_memories_scope
    ON business_memories(business_id, scope_type, scope_id);

CREATE TABLE IF NOT EXISTS document_classifications (
    id             {t["id"]},
    business_id    {t["ref"]} NOT NULL,
    document_id    {t["ref"]} NOT NULL,
    detected_kind  TEXT NOT NULL,
    confirmed_kind TEXT,
    confidence     {t["real"]},
    method         TEXT NOT NULL,
    reason         TEXT,
    created_at     {t["timestamp"]} NOT NULL,
    confirmed_at   {t["timestamp"]},
    FOREIGN KEY (business_id, document_id)
        REFERENCES documents(business_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_document_classifications_document
    ON document_classifications(business_id, document_id, created_at);
"""
    )
    columns = _column_names(conn, "invoices")
    if "source" not in columns:
        conn.execute(
            "ALTER TABLE invoices ADD COLUMN source "
            "TEXT NOT NULL DEFAULT 'noesis'"
        )
    if "external_number" not in columns:
        conn.execute(
            "ALTER TABLE invoices ADD COLUMN external_number TEXT"
        )


def _downgrade_companion_memory(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_document_classifications_document")
    conn.execute("DROP TABLE IF EXISTS document_classifications")
    conn.execute("DROP INDEX IF EXISTS idx_business_memories_scope")
    conn.execute("DROP TABLE IF EXISTS business_memories")
    conn.execute("DROP INDEX IF EXISTS idx_assistant_messages_business")
    conn.execute("DROP TABLE IF EXISTS assistant_messages")
    if conn.dialect == "postgres":
        conn.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS external_number")
        conn.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS source")
    # SQLite conserva las columnas para evitar reconstruir invoices.


def _upgrade_autonomy_control(conn) -> None:
    """Permisos configurables y trazabilidad de las acciones de Noesis.

    Los límites críticos no dependen solo de la interfaz: ``db.py`` valida qué
    modos admite cada acción antes de persistirlos. El registro de acciones deja
    constancia de qué propuso, aprobó o ejecutó el asistente.
    """
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS automation_permissions (
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    action_key  TEXT NOT NULL,
    mode        TEXT NOT NULL,
    created_at  {t["timestamp"]} NOT NULL,
    updated_at  {t["timestamp"]} NOT NULL,
    PRIMARY KEY (business_id, action_key)
);
CREATE INDEX IF NOT EXISTS idx_automation_permissions_business
    ON automation_permissions(business_id, action_key);

CREATE TABLE IF NOT EXISTS assistant_actions (
    id           {t["id"]},
    business_id  {t["ref"]} NOT NULL REFERENCES businesses(id),
    action_key   TEXT NOT NULL,
    risk_level   TEXT NOT NULL,
    status       TEXT NOT NULL,
    summary      TEXT NOT NULL,
    target_type  TEXT,
    target_id    {t["ref"]},
    payload      TEXT,
    requested_by TEXT NOT NULL DEFAULT 'noesis',
    approved_by  TEXT,
    created_at   {t["timestamp"]} NOT NULL,
    approved_at  {t["timestamp"]},
    executed_at  {t["timestamp"]},
    error        TEXT
);
CREATE INDEX IF NOT EXISTS idx_assistant_actions_business
    ON assistant_actions(business_id, created_at, id);
"""
    )


def _downgrade_autonomy_control(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_assistant_actions_business")
    conn.execute("DROP TABLE IF EXISTS assistant_actions")
    conn.execute("DROP INDEX IF EXISTS idx_automation_permissions_business")
    conn.execute("DROP TABLE IF EXISTS automation_permissions")


def _upgrade_operating_spine(conn) -> None:
    """Une proyecto, trabajo, gastos, documentos y tareas de campo."""
    t = _types(conn.dialect)
    for table in ("jobs", "expenses", "documents"):
        if "project_id" not in _column_names(conn, table):
            conn.execute(
                f"ALTER TABLE {table} ADD COLUMN project_id {t['ref']}"
            )
    conn.executescript(
        f"""
CREATE UNIQUE INDEX IF NOT EXISTS uq_jobs_business_id
    ON jobs(business_id, id);
CREATE INDEX IF NOT EXISTS idx_jobs_project
    ON jobs(business_id, project_id, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_expenses_project
    ON expenses(business_id, project_id, spent_on);
CREATE INDEX IF NOT EXISTS idx_documents_project
    ON documents(business_id, project_id, created_at);

CREATE TABLE IF NOT EXISTS project_tasks (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL,
    project_id  {t["ref"]} NOT NULL,
    job_id      {t["ref"]},
    worker_id   {t["ref"]},
    title       TEXT NOT NULL,
    note        TEXT,
    kind        TEXT NOT NULL DEFAULT 'tarea',
    status      TEXT NOT NULL DEFAULT 'pendiente',
    due_on      TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    updated_at  {t["timestamp"]} NOT NULL,
    completed_at {t["timestamp"]},
    FOREIGN KEY (business_id, project_id)
        REFERENCES projects(business_id, id) ON DELETE CASCADE,
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id),
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_project_tasks_project
    ON project_tasks(business_id, project_id, status, due_on);
CREATE INDEX IF NOT EXISTS idx_project_tasks_worker
    ON project_tasks(business_id, worker_id, status, due_on);
"""
    )
    if conn.dialect == "postgres":
        for table in ("jobs", "expenses", "documents"):
            constraint = f"{table}_project_same_business"
            conn.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {constraint}")
            conn.execute(
                f"ALTER TABLE {table} ADD CONSTRAINT {constraint} "
                "FOREIGN KEY (business_id, project_id) "
                "REFERENCES projects(business_id, id)"
            )
    else:
        for table in ("jobs", "expenses", "documents"):
            for event in ("INSERT", "UPDATE"):
                conn.executescript(
                    _sqlite_tenant_trigger(
                        table, "project_id", "projects", event
                    )
                )
        for event in ("INSERT", "UPDATE"):
            for column, parent in (
                ("project_id", "projects"),
                ("job_id", "jobs"),
                ("worker_id", "workers"),
            ):
                conn.executescript(
                    _sqlite_tenant_trigger(
                        "project_tasks", column, parent, event
                    )
                )


def _downgrade_operating_spine(conn) -> None:
    for table in ("project_tasks", "jobs", "expenses", "documents"):
        for column in ("project_id", "job_id", "worker_id"):
            for event in ("insert", "update"):
                conn.execute(
                    "DROP TRIGGER IF EXISTS "
                    f"{table}_{column}_same_business_{event}"
                )
    conn.execute("DROP INDEX IF EXISTS idx_project_tasks_worker")
    conn.execute("DROP INDEX IF EXISTS idx_project_tasks_project")
    conn.execute("DROP TABLE IF EXISTS project_tasks")
    conn.execute("DROP INDEX IF EXISTS idx_documents_project")
    conn.execute("DROP INDEX IF EXISTS idx_expenses_project")
    conn.execute("DROP INDEX IF EXISTS idx_jobs_project")
    if conn.dialect == "postgres":
        for table in ("jobs", "expenses", "documents"):
            conn.execute(
                f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS "
                f"{table}_project_same_business"
            )
            conn.execute(
                f"ALTER TABLE {table} DROP COLUMN IF EXISTS project_id"
            )
    # SQLite conserva las columnas anulables para evitar reconstruir tablas con
    # datos fiscales, documentos o fichajes ya existentes.


def _upgrade_gestoria_deliveries(conn) -> None:
    """Versiona los paquetes compartidos y deja rastro de cada entrega."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS gestoria_deliveries (
    id             {t["id"]},
    business_id    {t["ref"]} NOT NULL REFERENCES businesses(id),
    period_label   TEXT NOT NULL,
    version        INTEGER NOT NULL,
    status         TEXT NOT NULL DEFAULT 'preparado',
    source_hash    TEXT NOT NULL,
    artifact_hash  TEXT NOT NULL,
    file_size      INTEGER NOT NULL,
    manifest       TEXT NOT NULL,
    prepared_at    {t["timestamp"]} NOT NULL,
    notified_at    {t["timestamp"]},
    downloaded_at  {t["timestamp"]},
    UNIQUE (business_id, period_label, version)
);
CREATE INDEX IF NOT EXISTS idx_gestoria_deliveries_business
    ON gestoria_deliveries(business_id, period_label, version);
"""
    )


def _downgrade_gestoria_deliveries(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_gestoria_deliveries_business")
    conn.execute("DROP TABLE IF EXISTS gestoria_deliveries")


def _upgrade_field_work_close(conn) -> None:
    """Cierra cada trabajo con costes, evidencias, conformidad y factura borrador.

    Son registros operativos separados del fichaje legal: nunca se reescribe la
    jornada para cuadrar el cierre de un trabajo.
    """
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS job_materials (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL,
    job_id      {t["ref"]} NOT NULL,
    worker_id   {t["ref"]},
    description TEXT NOT NULL,
    quantity    {t["real"]} NOT NULL DEFAULT 1,
    unit_cost   {t["real"]} NOT NULL DEFAULT 0,
    total       {t["real"]} NOT NULL DEFAULT 0,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id),
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_job_materials_job
    ON job_materials(business_id, job_id, created_at);

CREATE TABLE IF NOT EXISTS job_updates (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL,
    job_id      {t["ref"]} NOT NULL,
    worker_id   {t["ref"]},
    document_id {t["ref"]},
    kind        TEXT NOT NULL,
    body        TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id),
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id),
    FOREIGN KEY (business_id, document_id)
        REFERENCES documents(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_job_updates_job
    ON job_updates(business_id, job_id, created_at);

CREATE TABLE IF NOT EXISTS job_completions (
    id                {t["id"]},
    business_id       {t["ref"]} NOT NULL,
    job_id            {t["ref"]} NOT NULL,
    worker_id         {t["ref"]},
    invoice_id        {t["ref"]},
    status            TEXT NOT NULL DEFAULT 'pendiente_cliente',
    summary           TEXT,
    customer_name     TEXT,
    customer_note     TEXT,
    signature_data    TEXT,
    signature_hash    TEXT,
    signer_ip_hash    TEXT,
    signer_user_agent TEXT,
    source            TEXT NOT NULL DEFAULT 'trabajador',
    created_at        {t["timestamp"]} NOT NULL,
    confirmed_at      {t["timestamp"]},
    rejected_at       {t["timestamp"]},
    UNIQUE (business_id, job_id),
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id),
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_job_completions_status
    ON job_completions(business_id, status, created_at);
"""
    )
    if conn.dialect == "sqlite":
        relations = {
            "job_materials": (("job_id", "jobs"), ("worker_id", "workers")),
            "job_updates": (
                ("job_id", "jobs"), ("worker_id", "workers"),
                ("document_id", "documents"),
            ),
            "job_completions": (
                ("job_id", "jobs"), ("worker_id", "workers"),
                ("invoice_id", "invoices"),
            ),
        }
        for table, columns in relations.items():
            for event in ("INSERT", "UPDATE"):
                for column, parent in columns:
                    conn.executescript(
                        _sqlite_tenant_trigger(table, column, parent, event)
                    )


def _downgrade_field_work_close(conn) -> None:
    for table in ("job_materials", "job_updates", "job_completions"):
        for column in ("job_id", "worker_id", "document_id", "invoice_id"):
            for event in ("insert", "update"):
                conn.execute(
                    "DROP TRIGGER IF EXISTS "
                    f"{table}_{column}_same_business_{event}"
                )
    conn.execute("DROP INDEX IF EXISTS idx_job_completions_status")
    conn.execute("DROP TABLE IF EXISTS job_completions")
    conn.execute("DROP INDEX IF EXISTS idx_job_updates_job")
    conn.execute("DROP TABLE IF EXISTS job_updates")
    conn.execute("DROP INDEX IF EXISTS idx_job_materials_job")
    conn.execute("DROP TABLE IF EXISTS job_materials")


def _upgrade_client_preferences(conn) -> None:
    """Preferencias confirmadas que mandan sobre cualquier patrón observado."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS client_preferences (
    business_id             {t["ref"]} NOT NULL,
    client_id               {t["ref"]} NOT NULL,
    preferred_channel       TEXT,
    preferred_contact_window TEXT,
    payment_terms_days      INTEGER,
    note                    TEXT,
    source                  TEXT NOT NULL DEFAULT 'manual',
    updated_at              {t["timestamp"]} NOT NULL,
    PRIMARY KEY (business_id, client_id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_client_preferences_business
    ON client_preferences(business_id, updated_at);
"""
    )
    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger(
                    "client_preferences", "client_id", "clients", event
                )
            )


def _downgrade_client_preferences(conn) -> None:
    for event in ("insert", "update"):
        conn.execute(
            "DROP TRIGGER IF EXISTS "
            f"client_preferences_client_id_same_business_{event}"
        )
    conn.execute("DROP INDEX IF EXISTS idx_client_preferences_business")
    conn.execute("DROP TABLE IF EXISTS client_preferences")


def _upgrade_integration_control(conn) -> None:
    """Preferencias de servicios externos, sin guardar credenciales del proveedor.

    ``default`` conserva el comportamiento previo de cada instalación. Los demás
    modos permiten que cada negocio active, rechace o muestre interés de forma
    explícita, siempre sin convertir una preferencia en permiso irreversible.
    """
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS integration_settings (
    business_id    {t["ref"]} NOT NULL REFERENCES businesses(id),
    integration_key TEXT NOT NULL,
    mode           TEXT NOT NULL DEFAULT 'default',
    last_error     TEXT,
    last_checked_at {t["timestamp"]},
    updated_at     {t["timestamp"]} NOT NULL,
    PRIMARY KEY (business_id, integration_key),
    CHECK (mode IN ('default', 'enabled', 'disabled', 'requested'))
);
CREATE INDEX IF NOT EXISTS idx_integration_settings_business
    ON integration_settings(business_id, updated_at);
"""
    )


def _downgrade_integration_control(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_integration_settings_business")
    conn.execute("DROP TABLE IF EXISTS integration_settings")


def _upgrade_calendar_feed(conn) -> None:
    """Enlace privado y revocable para suscribir la agenda sin OAuth externo."""
    if "calendar_token" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN calendar_token TEXT")
    conn.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_businesses_calendar_token "
        "ON businesses(calendar_token)"
    )


def _downgrade_calendar_feed(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS uq_businesses_calendar_token")
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE businesses DROP COLUMN IF EXISTS calendar_token"
        )
    # SQLite conserva la columna para no reconstruir la tabla businesses.


def _upgrade_bank_reconciliation(conn) -> None:
    """Movimientos importados y confirmación humana de cobros sugeridos."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS bank_transactions (
    id                   {t["id"]},
    business_id          {t["ref"]} NOT NULL REFERENCES businesses(id),
    import_hash          TEXT NOT NULL,
    booked_on            TEXT NOT NULL,
    amount               {t["real"]} NOT NULL,
    currency             TEXT NOT NULL DEFAULT 'EUR',
    description          TEXT,
    counterparty         TEXT,
    reference            TEXT,
    status               TEXT NOT NULL DEFAULT 'imported'
                         CHECK (status IN ('imported', 'suggested', 'confirmed', 'ignored')),
    suggested_invoice_id {t["ref"]},
    match_score          INTEGER,
    match_reason         TEXT,
    confirmed_at         {t["timestamp"]},
    created_at           {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, import_hash),
    FOREIGN KEY (business_id, suggested_invoice_id)
        REFERENCES invoices(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_business
    ON bank_transactions(business_id, booked_on, id);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_status
    ON bank_transactions(business_id, status, id);
"""
    )
    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger(
                    "bank_transactions", "suggested_invoice_id", "invoices", event
                )
            )


def _downgrade_bank_reconciliation(conn) -> None:
    for event in ("insert", "update"):
        conn.execute(
            "DROP TRIGGER IF EXISTS "
            f"bank_transactions_suggested_invoice_id_same_business_{event}"
        )
    conn.execute("DROP INDEX IF EXISTS idx_bank_transactions_status")
    conn.execute("DROP INDEX IF EXISTS idx_bank_transactions_business")
    conn.execute("DROP TABLE IF EXISTS bank_transactions")


def _upgrade_email_outbox(conn) -> None:
    """Correo durable: persistir antes de SMTP y reintentar sin duplicar."""
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS email_outbox (
    id               {t["id"]},
    business_id      {t["ref"]} REFERENCES businesses(id),
    to_email         TEXT NOT NULL,
    subject          TEXT NOT NULL,
    text_body        TEXT NOT NULL,
    html_body        TEXT,
    idempotency_key  TEXT UNIQUE,
    status           TEXT NOT NULL DEFAULT 'queued'
                     CHECK (status IN ('queued', 'processing', 'retrying', 'sent', 'failed')),
    attempts         INTEGER NOT NULL DEFAULT 0,
    max_attempts     INTEGER NOT NULL DEFAULT 6,
    next_attempt_at  {t["timestamp"]} NOT NULL,
    locked_at        {t["timestamp"]},
    last_error       TEXT,
    sent_at          {t["timestamp"]},
    created_at       {t["timestamp"]} NOT NULL,
    updated_at       {t["timestamp"]} NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email_outbox_due
    ON email_outbox(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_email_outbox_business
    ON email_outbox(business_id, created_at);
"""
    )


def _downgrade_email_outbox(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_email_outbox_business")
    conn.execute("DROP INDEX IF EXISTS idx_email_outbox_due")
    conn.execute("DROP TABLE IF EXISTS email_outbox")


def _upgrade_onboarding_operations(conn) -> None:
    """Preferencia real de vencimiento usada al emitir las facturas del negocio."""
    if "default_payment_term_days" not in _column_names(conn, "businesses"):
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN default_payment_term_days "
            "INTEGER NOT NULL DEFAULT 15"
        )


def _downgrade_onboarding_operations(conn) -> None:
    if conn.dialect == "postgres":
        conn.execute(
            "ALTER TABLE businesses DROP COLUMN IF EXISTS "
            "default_payment_term_days"
        )
    # SQLite conserva la columna para evitar reconstruir businesses.


Migration = tuple[int, str, Callable, Callable]
MIGRATIONS: tuple[Migration, ...] = (
    (1, "esquema_inicial", _upgrade_initial, _downgrade_initial),
    (2, "integridad_multiempresa", _upgrade_tenant_integrity, _downgrade_tenant_integrity),
    (3, "cola_whatsapp_durable", _upgrade_whatsapp_outbox, _downgrade_whatsapp_outbox),
    (4, "panel_personalizable", _upgrade_panel_layout, _downgrade_panel_layout),
    (5, "equipo_fichaje", _upgrade_team_clockins, _downgrade_team_clockins),
    (6, "fichaje_inalterable", _upgrade_immutable_clockins, _downgrade_immutable_clockins),
    (7, "verifactu_fase1", _upgrade_verifactu_phase1, _downgrade_verifactu_phase1),
    (8, "backups_verificados", _upgrade_verified_backups, _downgrade_verified_backups),
    (9, "verifactu_fase2", _upgrade_verifactu_phase2, _downgrade_verifactu_phase2),
    (10, "datos_cobro", _upgrade_payment_details, _downgrade_payment_details),
    (11, "cobros_parciales", _upgrade_partial_payments, _downgrade_partial_payments),
    (12, "gasto_por_foto", _upgrade_expense_from_photo, _downgrade_expense_from_photo),
    (13, "recordatorios_cobro", _upgrade_payment_reminders, _downgrade_payment_reminders),
    (14, "cerebro_whatsapp", _upgrade_whatsapp_brain, _downgrade_whatsapp_brain),
    (15, "gestoria", _upgrade_gestoria, _downgrade_gestoria),
    (16, "ciclo_webhooks", _upgrade_webhook_lifecycle, _downgrade_webhook_lifecycle),
    (17, "proveedores_recibidas", _upgrade_received_invoices, _downgrade_received_invoices),
    (18, "plataforma_base", _upgrade_platform_base, _downgrade_platform_base),
    (19, "proyectos_rentables", _upgrade_projects, _downgrade_projects),
    (20, "nivel_explicacion", _upgrade_explanation_level, _downgrade_explanation_level),
    (21, "memoria_noesis", _upgrade_companion_memory, _downgrade_companion_memory),
    (22, "control_autonomia", _upgrade_autonomy_control, _downgrade_autonomy_control),
    (23, "columna_operativa", _upgrade_operating_spine, _downgrade_operating_spine),
    (24, "entregas_gestoria", _upgrade_gestoria_deliveries, _downgrade_gestoria_deliveries),
    (25, "cierre_trabajo_campo", _upgrade_field_work_close, _downgrade_field_work_close),
    (26, "preferencias_cliente", _upgrade_client_preferences, _downgrade_client_preferences),
    (27, "control_integraciones", _upgrade_integration_control, _downgrade_integration_control),
    (28, "calendario_privado", _upgrade_calendar_feed, _downgrade_calendar_feed),
    (29, "conciliacion_bancaria", _upgrade_bank_reconciliation, _downgrade_bank_reconciliation),
    (30, "correo_durable", _upgrade_email_outbox, _downgrade_email_outbox),
    (31, "alta_operativa", _upgrade_onboarding_operations, _downgrade_onboarding_operations),
)
LATEST_VERSION = MIGRATIONS[-1][0]


def _ensure_version_table(conn) -> None:
    timestamp = _types(conn.dialect)["timestamp"]
    conn.execute(
        "CREATE TABLE IF NOT EXISTS schema_migrations ("
        "version INTEGER PRIMARY KEY, name TEXT NOT NULL, "
        f"applied_at {timestamp} NOT NULL)"
    )


def _version_table_exists(conn) -> bool:
    if conn.dialect == "sqlite":
        row = conn.execute(
            "SELECT 1 AS found FROM sqlite_master "
            "WHERE type='table' AND name='schema_migrations'"
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT 1 AS found FROM information_schema.tables "
            "WHERE table_schema=current_schema() "
            "AND table_name='schema_migrations'"
        ).fetchone()
    return bool(row)


def _current_version(conn) -> int:
    if not _version_table_exists(conn):
        return 0
    row = conn.execute(
        "SELECT COALESCE(MAX(version), 0) AS version FROM schema_migrations"
    ).fetchone()
    return int(row["version"])


def current_version() -> int:
    from . import db

    with db.get_conn() as conn:
        return _current_version(conn)


def current_version_connection(conn) -> int:
    """Consulta la versión dentro de una conexión o esquema ya seleccionado."""
    return _current_version(conn)


def is_current() -> bool:
    try:
        return current_version() == LATEST_VERSION
    except Exception:
        return False


def upgrade_connection(conn, target: int | None = None) -> int:
    """Aplica migraciones sobre una conexión existente.

    La restauración de Postgres la usa con un ``search_path`` temporal para no
    escribir nunca en el esquema real durante la verificación.
    """
    target = LATEST_VERSION if target is None else target
    if target < 0 or target > LATEST_VERSION:
        raise ValueError(f"Versión objetivo no válida: {target}")
    _ensure_version_table(conn)
    current = _current_version(conn)
    for version, name, apply, _revert in MIGRATIONS:
        if current < version <= target:
            apply(conn)
            conn.execute(
                "INSERT INTO schema_migrations (version, name, applied_at) "
                "VALUES (?, ?, ?)",
                (version, name, datetime.now().isoformat(timespec="seconds")),
            )
            current = version
    return current


def upgrade(target: int | None = None) -> int:
    from . import db

    with db.get_conn() as conn:
        current = upgrade_connection(conn, target)
    return current


def downgrade(target: int | None = None) -> int:
    from . import db

    with db.get_conn() as conn:
        current = _current_version(conn)
        target = max(0, current - 1) if target is None else target
        if target < 0 or target >= current:
            raise ValueError(f"Versión objetivo no válida: {target}")
        for version, _name, _apply, revert in reversed(MIGRATIONS):
            if target < version <= current:
                revert(conn)
                conn.execute(
                    "DELETE FROM schema_migrations WHERE version=?", (version,)
                )
        return target


def main() -> None:
    parser = argparse.ArgumentParser(description="Migraciones de Noesis")
    parser.add_argument("action", choices=("upgrade", "downgrade", "current"))
    parser.add_argument("target", nargs="?", type=int)
    args = parser.parse_args()
    if args.action == "upgrade":
        version = upgrade(args.target)
    elif args.action == "downgrade":
        version = downgrade(args.target)
    else:
        version = current_version()
    print(f"Esquema en versión {version}/{LATEST_VERSION}")


if __name__ == "__main__":
    main()
