"""Migraciones versionadas, ligeras y compatibles con SQLite/Postgres."""

from __future__ import annotations

import argparse
from collections.abc import Callable
from datetime import datetime


def _types(dialect: str) -> dict[str, str]:
    if dialect == "postgres":
        return {
            "id": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "ref": "BIGINT",
            "real": "DOUBLE PRECISION",
            "timestamp": "TIMESTAMP WITHOUT TIME ZONE",
            "boolean": "BOOLEAN",
        }
    return {
        "id": "INTEGER PRIMARY KEY AUTOINCREMENT",
        "ref": "INTEGER",
        "real": "REAL",
        "timestamp": "TEXT",
        "boolean": "INTEGER",
    }


def _initial_schema(dialect: str) -> str:
    t = _types(dialect)
    return f"""
CREATE TABLE IF NOT EXISTS businesses (
    id                      {t["id"]},
    name                    TEXT NOT NULL,
    owner_email             TEXT,
    sector                  TEXT,
    nif                     TEXT,
    address                 TEXT,
    default_vat             {t["real"]} NOT NULL DEFAULT 21,
    default_irpf            {t["real"]} NOT NULL DEFAULT 0,
    whatsapp_phone          TEXT,
    whatsapp_status         TEXT NOT NULL DEFAULT 'no_conectado',
    onboarding_done         {t["boolean"]} NOT NULL DEFAULT FALSE,
    plan                    TEXT NOT NULL DEFAULT 'trial',
    subscription_status     TEXT NOT NULL DEFAULT 'trial',
    trial_ends_at           {t["timestamp"]},
    stripe_customer_id      TEXT,
    stripe_subscription_id  TEXT,
    whatsapp_phone_norm     TEXT,
    team_size               TEXT,
    province                TEXT,
    primary_goal            TEXT,
    invoice_template        TEXT NOT NULL DEFAULT 'clasica',
    brand_color             TEXT,
    logo_data               TEXT,
    logo_mime               TEXT,
    created_at              {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id              {t["id"]},
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    business_id     {t["ref"]} NOT NULL REFERENCES businesses(id),
    is_admin        {t["boolean"]} NOT NULL DEFAULT FALSE,
    session_version INTEGER NOT NULL DEFAULT 0,
    created_at      {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    phone       TEXT,
    address     TEXT,
    zone        TEXT,
    nif         TEXT,
    email       TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id              {t["id"]},
    business_id     {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id       {t["ref"]},
    description     TEXT NOT NULL,
    scheduled_for   {t["timestamp"]},
    zone            TEXT,
    price_estimate  {t["real"]},
    status          TEXT NOT NULL DEFAULT 'pendiente',
    created_at      {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id                  {t["id"]},
    business_id         {t["ref"]} NOT NULL REFERENCES businesses(id),
    number              TEXT,
    client_id           {t["ref"]},
    concept             TEXT NOT NULL,
    base                {t["real"]} NOT NULL,
    vat_rate            {t["real"]} NOT NULL,
    vat_amount          {t["real"]} NOT NULL,
    irpf_rate           {t["real"]} NOT NULL DEFAULT 0,
    irpf_amount         {t["real"]} NOT NULL DEFAULT 0,
    total               {t["real"]} NOT NULL,
    status              TEXT NOT NULL DEFAULT 'borrador',
    due_date            {t["timestamp"]},
    issued_at           {t["timestamp"]},
    paid_at             {t["timestamp"]},
    last_reminder_at    {t["timestamp"]},
    reminders_sent      INTEGER NOT NULL DEFAULT 0,
    issuer_name         TEXT,
    issuer_nif          TEXT,
    issuer_address      TEXT,
    recipient_name      TEXT,
    recipient_nif       TEXT,
    recipient_address   TEXT,
    created_at          {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS expenses (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    concept     TEXT NOT NULL,
    amount      {t["real"]} NOT NULL,
    vat_rate    {t["real"]},
    category    TEXT,
    spent_on    {t["timestamp"]},
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    number      TEXT,
    client_id   {t["ref"]},
    concept     TEXT NOT NULL,
    base        {t["real"]} NOT NULL,
    vat_rate    {t["real"]} NOT NULL,
    vat_amount  {t["real"]} NOT NULL,
    irpf_rate   {t["real"]} NOT NULL DEFAULT 0,
    irpf_amount {t["real"]} NOT NULL DEFAULT 0,
    total       {t["real"]} NOT NULL,
    status      TEXT NOT NULL DEFAULT 'borrador',
    valid_until {t["timestamp"]},
    invoice_id  {t["ref"]},
    created_at  {t["timestamp"]} NOT NULL,
    accepted_at {t["timestamp"]},
    UNIQUE (business_id, id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);

CREATE TABLE IF NOT EXISTS password_resets (
    id          {t["id"]},
    user_id     {t["ref"]} NOT NULL REFERENCES users(id),
    token_hash  TEXT NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    used        {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS document_sequences (
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    kind        TEXT NOT NULL,
    year        INTEGER NOT NULL,
    last_number INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (business_id, kind, year)
);

CREATE TABLE IF NOT EXISTS webhook_events (
    source      TEXT NOT NULL,
    event_id    TEXT NOT NULL,
    created_at  {t["timestamp"]} NOT NULL,
    PRIMARY KEY (source, event_id)
);

CREATE TABLE IF NOT EXISTS product_events (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    event_name  TEXT NOT NULL,
    event_data  TEXT,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS whatsapp_links (
    code_hash    TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    expires_at  {t["timestamp"]} NOT NULL,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS scheduled_job_runs (
    run_key     TEXT PRIMARY KEY,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_tokens (
    token       TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id   {t["ref"]} NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    revoked     {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS copilot_recommendations (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    topic       TEXT NOT NULL,
    summary     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'recomendado',
    created_at  {t["timestamp"]} NOT NULL,
    updated_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id   {t["ref"]},
    invoice_id  {t["ref"]},
    kind        TEXT NOT NULL DEFAULT 'documento',
    filename    TEXT NOT NULL,
    stored_name TEXT NOT NULL,
    mime        TEXT,
    size        INTEGER NOT NULL DEFAULT 0,
    ocr_text    TEXT,
    ocr_amount  {t["real"]},
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);
"""


LEGACY_COLUMNS = {
    "businesses": {
        "plan": "TEXT NOT NULL DEFAULT 'trial'",
        "subscription_status": "TEXT NOT NULL DEFAULT 'trial'",
        "trial_ends_at": "TEXT",
        "stripe_customer_id": "TEXT",
        "stripe_subscription_id": "TEXT",
        "whatsapp_phone_norm": "TEXT",
        "team_size": "TEXT",
        "province": "TEXT",
        "primary_goal": "TEXT",
        "invoice_template": "TEXT NOT NULL DEFAULT 'clasica'",
        "brand_color": "TEXT",
        "logo_data": "TEXT",
        "logo_mime": "TEXT",
        "panel_layout": "TEXT",
    },
    "users": {
        "is_admin": "INTEGER NOT NULL DEFAULT 0",
        "session_version": "INTEGER NOT NULL DEFAULT 0",
    },
    "clients": {"nif": "TEXT", "email": "TEXT"},
    "invoices": {
        "last_reminder_at": "TEXT",
        "reminders_sent": "INTEGER NOT NULL DEFAULT 0",
        "issuer_name": "TEXT",
        "issuer_nif": "TEXT",
        "issuer_address": "TEXT",
        "recipient_name": "TEXT",
        "recipient_nif": "TEXT",
        "recipient_address": "TEXT",
    },
}


def _column_names(conn, table: str) -> set[str]:
    if conn.dialect == "sqlite":
        return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}
    rows = conn.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema='public' AND table_name=?",
        (table,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _upgrade_initial(conn) -> None:
    conn.executescript(_initial_schema(conn.dialect))
    # Adopta instalaciones SQLite anteriores sin volver a ALTERar en cada arranque.
    if conn.dialect == "sqlite":
        for table, columns in LEGACY_COLUMNS.items():
            present = _column_names(conn, table)
            for column, declaration in columns.items():
                if column not in present:
                    conn.execute(
                        f"ALTER TABLE {table} ADD COLUMN {column} {declaration}"
                    )


def _downgrade_initial(conn) -> None:
    for table in (
        "documents", "copilot_recommendations", "portal_tokens",
        "scheduled_job_runs", "whatsapp_links", "product_events",
        "webhook_events", "document_sequences", "password_resets", "quotes",
        "expenses", "invoices", "jobs", "clients", "users", "businesses",
    ):
        conn.execute(f"DROP TABLE IF EXISTS {table}")


INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_clients_business ON clients(business_id)",
    "CREATE INDEX IF NOT EXISTS idx_jobs_business_date ON jobs(business_id, scheduled_for)",
    "CREATE INDEX IF NOT EXISTS idx_invoices_business_status ON invoices(business_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_expenses_business_date ON expenses(business_id, spent_on)",
    "CREATE INDEX IF NOT EXISTS idx_quotes_business_status ON quotes(business_id, status)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_invoice_number "
    "ON invoices(business_id, number) WHERE number IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_quote_number "
    "ON quotes(business_id, number) WHERE number IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_whatsapp_phone "
    "ON businesses(whatsapp_phone_norm) WHERE whatsapp_phone_norm IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_clients_business_id ON clients(business_id, id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_invoices_business_id ON invoices(business_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_portal_tokens_client ON portal_tokens(business_id, client_id)",
    "CREATE INDEX IF NOT EXISTS idx_copilot_recs_business "
    "ON copilot_recommendations(business_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_product_events_business_date "
    "ON product_events(business_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_product_events_name_date "
    "ON product_events(event_name, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_documents_business ON documents(business_id)",
    "CREATE INDEX IF NOT EXISTS idx_documents_client ON documents(business_id, client_id)",
)


SQLITE_TENANT_RELATIONS = (
    ("jobs", "client_id", "clients"),
    ("invoices", "client_id", "clients"),
    ("quotes", "client_id", "clients"),
    ("quotes", "invoice_id", "invoices"),
    ("documents", "client_id", "clients"),
    ("documents", "invoice_id", "invoices"),
    ("portal_tokens", "client_id", "clients"),
)


def _sqlite_tenant_trigger(table: str, column: str, parent: str, event: str) -> str:
    name = f"{table}_{column}_same_business_{event.lower()}"
    timing = (
        f"BEFORE INSERT ON {table}"
        if event == "INSERT"
        else f"BEFORE UPDATE OF business_id, {column} ON {table}"
    )
    return f"""
CREATE TRIGGER IF NOT EXISTS {name}
{timing}
WHEN NEW.{column} IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM {parent}
    WHERE id=NEW.{column} AND business_id=NEW.business_id
)
BEGIN
    SELECT RAISE(ABORT, '{column} pertenece a otro negocio');
END;
"""


def _upgrade_tenant_integrity(conn) -> None:
    for statement in INDEXES:
        conn.execute(statement)
    # Las instalaciones SQLite heredadas no pueden añadir FKs con ALTER TABLE.
    # Estos triggers aplican la misma restricción a sus relaciones multiempresa.
    if conn.dialect == "sqlite":
        for table, column, parent in SQLITE_TENANT_RELATIONS:
            for event in ("INSERT", "UPDATE"):
                conn.executescript(
                    _sqlite_tenant_trigger(table, column, parent, event)
                )


def _downgrade_tenant_integrity(conn) -> None:
    if conn.dialect == "sqlite":
        for table, column, _parent in SQLITE_TENANT_RELATIONS:
            conn.execute(
                f"DROP TRIGGER IF EXISTS "
                f"{table}_{column}_same_business_insert"
            )
            conn.execute(
                f"DROP TRIGGER IF EXISTS "
                f"{table}_{column}_same_business_update"
            )
    for statement in reversed(INDEXES):
        name = statement.split("INDEX IF NOT EXISTS ", 1)[1].split(" ", 1)[0]
        conn.execute(f"DROP INDEX IF EXISTS {name}")


def _upgrade_whatsapp_outbox(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS whatsapp_outbox (
    id                  {t["id"]},
    business_id         {t["ref"]} REFERENCES businesses(id),
    to_phone            TEXT NOT NULL,
    message_type        TEXT NOT NULL,
    text_body           TEXT,
    template_name       TEXT,
    template_language   TEXT,
    template_params     TEXT,
    idempotency_key     TEXT UNIQUE,
    status              TEXT NOT NULL DEFAULT 'queued',
    attempts            INTEGER NOT NULL DEFAULT 0,
    max_attempts        INTEGER NOT NULL DEFAULT 5,
    next_attempt_at     {t["timestamp"]} NOT NULL,
    locked_at           {t["timestamp"]},
    meta_message_id     TEXT UNIQUE,
    last_error          TEXT,
    sent_at             {t["timestamp"]},
    delivered_at        {t["timestamp"]},
    read_at             {t["timestamp"]},
    created_at          {t["timestamp"]} NOT NULL,
    updated_at          {t["timestamp"]} NOT NULL,
    CHECK (message_type IN ('text', 'template')),
    CHECK (status IN ('queued', 'processing', 'retrying', 'sent',
                      'delivered', 'read', 'failed'))
);
"""
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_due "
        "ON whatsapp_outbox(status, next_attempt_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_business "
        "ON whatsapp_outbox(business_id, created_at)"
    )


def _downgrade_whatsapp_outbox(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_whatsapp_outbox_business")
    conn.execute("DROP INDEX IF EXISTS idx_whatsapp_outbox_due")
    conn.execute("DROP TABLE IF EXISTS whatsapp_outbox")


def _upgrade_panel_layout(conn) -> None:
    # Guarda cómo cada negocio ordena/oculta los bloques de su panel de inicio.
    if "panel_layout" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN panel_layout TEXT")


def _downgrade_panel_layout(conn) -> None:
    # SQLite no soporta DROP COLUMN en versiones antiguas; se deja la columna
    # (es nullable y opcional, no rompe nada al revertir).
    if conn.dialect != "sqlite":
        conn.execute("ALTER TABLE businesses DROP COLUMN IF EXISTS panel_layout")


Migration = tuple[int, str, Callable, Callable]
MIGRATIONS: tuple[Migration, ...] = (
    (1, "esquema_inicial", _upgrade_initial, _downgrade_initial),
    (2, "integridad_multiempresa", _upgrade_tenant_integrity, _downgrade_tenant_integrity),
    (3, "cola_whatsapp_durable", _upgrade_whatsapp_outbox, _downgrade_whatsapp_outbox),
    (4, "panel_personalizable", _upgrade_panel_layout, _downgrade_panel_layout),
)
LATEST_VERSION = MIGRATIONS[-1][0]


def _ensure_version_table(conn) -> None:
    timestamp = _types(conn.dialect)["timestamp"]
    conn.execute(
        "CREATE TABLE IF NOT EXISTS schema_migrations ("
        "version INTEGER PRIMARY KEY, name TEXT NOT NULL, "
        f"applied_at {timestamp} NOT NULL)"
    )


def _version_table_exists(conn) -> bool:
    if conn.dialect == "sqlite":
        row = conn.execute(
            "SELECT 1 AS found FROM sqlite_master "
            "WHERE type='table' AND name='schema_migrations'"
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT 1 AS found FROM information_schema.tables "
            "WHERE table_schema='public' AND table_name='schema_migrations'"
        ).fetchone()
    return bool(row)


def _current_version(conn) -> int:
    if not _version_table_exists(conn):
        return 0
    row = conn.execute(
        "SELECT COALESCE(MAX(version), 0) AS version FROM schema_migrations"
    ).fetchone()
    return int(row["version"])


def current_version() -> int:
    from . import db

    with db.get_conn() as conn:
        return _current_version(conn)


def is_current() -> bool:
    try:
        return current_version() == LATEST_VERSION
    except Exception:
        return False


def upgrade(target: int | None = None) -> int:
    from . import db

    target = LATEST_VERSION if target is None else target
    if target < 0 or target > LATEST_VERSION:
        raise ValueError(f"Versión objetivo no válida: {target}")
    with db.get_conn() as conn:
        _ensure_version_table(conn)
        current = _current_version(conn)
        for version, name, apply, _revert in MIGRATIONS:
            if current < version <= target:
                apply(conn)
                conn.execute(
                    "INSERT INTO schema_migrations (version, name, applied_at) "
                    "VALUES (?, ?, ?)",
                    (version, name, datetime.now().isoformat(timespec="seconds")),
                )
                current = version
    return current


def downgrade(target: int | None = None) -> int:
    from . import db

    with db.get_conn() as conn:
        current = _current_version(conn)
        target = max(0, current - 1) if target is None else target
        if target < 0 or target >= current:
            raise ValueError(f"Versión objetivo no válida: {target}")
        for version, _name, _apply, revert in reversed(MIGRATIONS):
            if target < version <= current:
                revert(conn)
                conn.execute(
                    "DELETE FROM schema_migrations WHERE version=?", (version,)
                )
        return target


def main() -> None:
    parser = argparse.ArgumentParser(description="Migraciones de Noesis")
    parser.add_argument("action", choices=("upgrade", "downgrade", "current"))
    parser.add_argument("target", nargs="?", type=int)
    args = parser.parse_args()
    if args.action == "upgrade":
        version = upgrade(args.target)
    elif args.action == "downgrade":
        version = downgrade(args.target)
    else:
        version = current_version()
    print(f"Esquema en versión {version}/{LATEST_VERSION}")


if __name__ == "__main__":
    main()
