"""Migraciones versionadas, ligeras y compatibles con SQLite/Postgres."""

from __future__ import annotations

import argparse
from collections.abc import Callable
from datetime import datetime

from .clockin_integrity import clockin_seal


def _types(dialect: str) -> dict[str, str]:
    if dialect == "postgres":
        return {
            "id": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "ref": "BIGINT",
            "real": "DOUBLE PRECISION",
            "timestamp": "TIMESTAMP WITHOUT TIME ZONE",
            "boolean": "BOOLEAN",
        }
    return {
        "id": "INTEGER PRIMARY KEY AUTOINCREMENT",
        "ref": "INTEGER",
        "real": "REAL",
        "timestamp": "TEXT",
        "boolean": "INTEGER",
    }


def _initial_schema(dialect: str) -> str:
    t = _types(dialect)
    return f"""
CREATE TABLE IF NOT EXISTS businesses (
    id                      {t["id"]},
    name                    TEXT NOT NULL,
    owner_email             TEXT,
    sector                  TEXT,
    nif                     TEXT,
    address                 TEXT,
    default_vat             {t["real"]} NOT NULL DEFAULT 21,
    default_irpf            {t["real"]} NOT NULL DEFAULT 0,
    whatsapp_phone          TEXT,
    whatsapp_status         TEXT NOT NULL DEFAULT 'no_conectado',
    onboarding_done         {t["boolean"]} NOT NULL DEFAULT FALSE,
    plan                    TEXT NOT NULL DEFAULT 'trial',
    subscription_status     TEXT NOT NULL DEFAULT 'trial',
    trial_ends_at           {t["timestamp"]},
    stripe_customer_id      TEXT,
    stripe_subscription_id  TEXT,
    whatsapp_phone_norm     TEXT,
    team_size               TEXT,
    province                TEXT,
    primary_goal            TEXT,
    invoice_template        TEXT NOT NULL DEFAULT 'clasica',
    brand_color             TEXT,
    logo_data               TEXT,
    logo_mime               TEXT,
    created_at              {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id              {t["id"]},
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    business_id     {t["ref"]} NOT NULL REFERENCES businesses(id),
    is_admin        {t["boolean"]} NOT NULL DEFAULT FALSE,
    session_version INTEGER NOT NULL DEFAULT 0,
    created_at      {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    phone       TEXT,
    address     TEXT,
    zone        TEXT,
    nif         TEXT,
    email       TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id              {t["id"]},
    business_id     {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id       {t["ref"]},
    description     TEXT NOT NULL,
    scheduled_for   {t["timestamp"]},
    zone            TEXT,
    price_estimate  {t["real"]},
    status          TEXT NOT NULL DEFAULT 'pendiente',
    created_at      {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id                  {t["id"]},
    business_id         {t["ref"]} NOT NULL REFERENCES businesses(id),
    number              TEXT,
    client_id           {t["ref"]},
    concept             TEXT NOT NULL,
    base                {t["real"]} NOT NULL,
    vat_rate            {t["real"]} NOT NULL,
    vat_amount          {t["real"]} NOT NULL,
    irpf_rate           {t["real"]} NOT NULL DEFAULT 0,
    irpf_amount         {t["real"]} NOT NULL DEFAULT 0,
    total               {t["real"]} NOT NULL,
    status              TEXT NOT NULL DEFAULT 'borrador',
    due_date            {t["timestamp"]},
    issued_at           {t["timestamp"]},
    paid_at             {t["timestamp"]},
    last_reminder_at    {t["timestamp"]},
    reminders_sent      INTEGER NOT NULL DEFAULT 0,
    issuer_name         TEXT,
    issuer_nif          TEXT,
    issuer_address      TEXT,
    recipient_name      TEXT,
    recipient_nif       TEXT,
    recipient_address   TEXT,
    created_at          {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS expenses (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    concept     TEXT NOT NULL,
    amount      {t["real"]} NOT NULL,
    vat_rate    {t["real"]},
    category    TEXT,
    spent_on    {t["timestamp"]},
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    number      TEXT,
    client_id   {t["ref"]},
    concept     TEXT NOT NULL,
    base        {t["real"]} NOT NULL,
    vat_rate    {t["real"]} NOT NULL,
    vat_amount  {t["real"]} NOT NULL,
    irpf_rate   {t["real"]} NOT NULL DEFAULT 0,
    irpf_amount {t["real"]} NOT NULL DEFAULT 0,
    total       {t["real"]} NOT NULL,
    status      TEXT NOT NULL DEFAULT 'borrador',
    valid_until {t["timestamp"]},
    invoice_id  {t["ref"]},
    created_at  {t["timestamp"]} NOT NULL,
    accepted_at {t["timestamp"]},
    UNIQUE (business_id, id),
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);

CREATE TABLE IF NOT EXISTS password_resets (
    id          {t["id"]},
    user_id     {t["ref"]} NOT NULL REFERENCES users(id),
    token_hash  TEXT NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    used        {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS document_sequences (
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    kind        TEXT NOT NULL,
    year        INTEGER NOT NULL,
    last_number INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (business_id, kind, year)
);

CREATE TABLE IF NOT EXISTS webhook_events (
    source      TEXT NOT NULL,
    event_id    TEXT NOT NULL,
    created_at  {t["timestamp"]} NOT NULL,
    PRIMARY KEY (source, event_id)
);

CREATE TABLE IF NOT EXISTS product_events (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    event_name  TEXT NOT NULL,
    event_data  TEXT,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS whatsapp_links (
    code_hash    TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    expires_at  {t["timestamp"]} NOT NULL,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS scheduled_job_runs (
    run_key     TEXT PRIMARY KEY,
    created_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_tokens (
    token       TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id   {t["ref"]} NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    revoked     {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id)
);

CREATE TABLE IF NOT EXISTS copilot_recommendations (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    topic       TEXT NOT NULL,
    summary     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'recomendado',
    created_at  {t["timestamp"]} NOT NULL,
    updated_at  {t["timestamp"]} NOT NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    client_id   {t["ref"]},
    invoice_id  {t["ref"]},
    kind        TEXT NOT NULL DEFAULT 'documento',
    filename    TEXT NOT NULL,
    stored_name TEXT NOT NULL,
    mime        TEXT,
    size        INTEGER NOT NULL DEFAULT 0,
    ocr_text    TEXT,
    ocr_amount  {t["real"]},
    note        TEXT,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, client_id)
        REFERENCES clients(business_id, id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id)
);
"""


LEGACY_COLUMNS = {
    "businesses": {
        "plan": "TEXT NOT NULL DEFAULT 'trial'",
        "subscription_status": "TEXT NOT NULL DEFAULT 'trial'",
        "trial_ends_at": "TEXT",
        "stripe_customer_id": "TEXT",
        "stripe_subscription_id": "TEXT",
        "whatsapp_phone_norm": "TEXT",
        "team_size": "TEXT",
        "province": "TEXT",
        "primary_goal": "TEXT",
        "invoice_template": "TEXT NOT NULL DEFAULT 'clasica'",
        "brand_color": "TEXT",
        "logo_data": "TEXT",
        "logo_mime": "TEXT",
        "panel_layout": "TEXT",
        "clockin_policy": "TEXT",
        "verifactu_enabled": "BOOLEAN NOT NULL DEFAULT FALSE",
    },
    "users": {
        "is_admin": "INTEGER NOT NULL DEFAULT 0",
        "session_version": "INTEGER NOT NULL DEFAULT 0",
    },
    "clients": {"nif": "TEXT", "email": "TEXT"},
    "jobs": {"worker_id": "INTEGER"},
    "invoices": {
        "last_reminder_at": "TEXT",
        "reminders_sent": "INTEGER NOT NULL DEFAULT 0",
        "issuer_name": "TEXT",
        "issuer_nif": "TEXT",
        "issuer_address": "TEXT",
        "recipient_name": "TEXT",
        "recipient_nif": "TEXT",
        "recipient_address": "TEXT",
    },
}


def _column_names(conn, table: str) -> set[str]:
    if conn.dialect == "sqlite":
        return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}
    rows = conn.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema=current_schema() AND table_name=?",
        (table,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _upgrade_initial(conn) -> None:
    conn.executescript(_initial_schema(conn.dialect))
    # Adopta instalaciones SQLite anteriores sin volver a ALTERar en cada arranque.
    if conn.dialect == "sqlite":
        for table, columns in LEGACY_COLUMNS.items():
            present = _column_names(conn, table)
            for column, declaration in columns.items():
                if column not in present:
                    conn.execute(
                        f"ALTER TABLE {table} ADD COLUMN {column} {declaration}"
                    )


def _downgrade_initial(conn) -> None:
    for table in (
        "documents", "copilot_recommendations", "portal_tokens",
        "scheduled_job_runs", "whatsapp_links", "product_events",
        "webhook_events", "document_sequences", "password_resets", "quotes",
        "expenses", "invoices", "jobs", "clients", "users", "businesses",
    ):
        conn.execute(f"DROP TABLE IF EXISTS {table}")


INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_clients_business ON clients(business_id)",
    "CREATE INDEX IF NOT EXISTS idx_jobs_business_date ON jobs(business_id, scheduled_for)",
    "CREATE INDEX IF NOT EXISTS idx_invoices_business_status ON invoices(business_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_expenses_business_date ON expenses(business_id, spent_on)",
    "CREATE INDEX IF NOT EXISTS idx_quotes_business_status ON quotes(business_id, status)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_invoice_number "
    "ON invoices(business_id, number) WHERE number IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_quote_number "
    "ON quotes(business_id, number) WHERE number IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_whatsapp_phone "
    "ON businesses(whatsapp_phone_norm) WHERE whatsapp_phone_norm IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_clients_business_id ON clients(business_id, id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_invoices_business_id ON invoices(business_id, id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_jobs_business_id ON jobs(business_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_portal_tokens_client ON portal_tokens(business_id, client_id)",
    "CREATE INDEX IF NOT EXISTS idx_copilot_recs_business "
    "ON copilot_recommendations(business_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_product_events_business_date "
    "ON product_events(business_id, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_product_events_name_date "
    "ON product_events(event_name, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_documents_business ON documents(business_id)",
    "CREATE INDEX IF NOT EXISTS idx_documents_client ON documents(business_id, client_id)",
    "CREATE INDEX IF NOT EXISTS idx_workers_business ON workers(business_id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_workers_business_phone "
    "ON workers(business_id, phone_norm) WHERE phone_norm IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS idx_jobs_worker ON jobs(business_id, worker_id)",
    "CREATE INDEX IF NOT EXISTS idx_clockins_worker "
    "ON worker_clockins(business_id, worker_id, at)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_clockins_business_id "
    "ON worker_clockins(business_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_clockin_corrections_clockin "
    "ON worker_clockin_corrections(business_id, clockin_id, id)",
    "CREATE INDEX IF NOT EXISTS idx_invoice_records_issuer "
    "ON invoice_records(business_id, issuer_nif, id)",
    "CREATE INDEX IF NOT EXISTS idx_invoice_events_business "
    "ON invoice_events(business_id, created_at, id)",
)


SQLITE_TENANT_RELATIONS = (
    ("jobs", "client_id", "clients"),
    ("jobs", "worker_id", "workers"),
    ("invoices", "client_id", "clients"),
    ("quotes", "client_id", "clients"),
    ("quotes", "invoice_id", "invoices"),
    ("documents", "client_id", "clients"),
    ("documents", "invoice_id", "invoices"),
    ("portal_tokens", "client_id", "clients"),
)


def _sqlite_tenant_trigger(table: str, column: str, parent: str, event: str) -> str:
    name = f"{table}_{column}_same_business_{event.lower()}"
    timing = (
        f"BEFORE INSERT ON {table}"
        if event == "INSERT"
        else f"BEFORE UPDATE OF business_id, {column} ON {table}"
    )
    return f"""
CREATE TRIGGER IF NOT EXISTS {name}
{timing}
WHEN NEW.{column} IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM {parent}
    WHERE id=NEW.{column} AND business_id=NEW.business_id
)
BEGIN
    SELECT RAISE(ABORT, '{column} pertenece a otro negocio');
END;
"""


def _upgrade_tenant_integrity(conn) -> None:
    for statement in INDEXES:
        table = statement.split(" ON ", 1)[1].split("(", 1)[0].strip()
        if _table_exists(conn, table):
            conn.execute(statement)
    # Las instalaciones SQLite heredadas no pueden añadir FKs con ALTER TABLE.
    # Estos triggers aplican la misma restricción a sus relaciones multiempresa.
    if conn.dialect == "sqlite":
        for table, column, parent in SQLITE_TENANT_RELATIONS:
            if not _table_exists(conn, table) or not _table_exists(conn, parent):
                continue
            for event in ("INSERT", "UPDATE"):
                conn.executescript(
                    _sqlite_tenant_trigger(table, column, parent, event)
                )


def _downgrade_tenant_integrity(conn) -> None:
    if conn.dialect == "sqlite":
        for table, column, _parent in SQLITE_TENANT_RELATIONS:
            conn.execute(
                f"DROP TRIGGER IF EXISTS "
                f"{table}_{column}_same_business_insert"
            )
            conn.execute(
                f"DROP TRIGGER IF EXISTS "
                f"{table}_{column}_same_business_update"
            )
    for statement in reversed(INDEXES):
        name = statement.split("INDEX IF NOT EXISTS ", 1)[1].split(" ", 1)[0]
        conn.execute(f"DROP INDEX IF EXISTS {name}")


def _upgrade_whatsapp_outbox(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS whatsapp_outbox (
    id                  {t["id"]},
    business_id         {t["ref"]} REFERENCES businesses(id),
    to_phone            TEXT NOT NULL,
    message_type        TEXT NOT NULL,
    text_body           TEXT,
    template_name       TEXT,
    template_language   TEXT,
    template_params     TEXT,
    idempotency_key     TEXT UNIQUE,
    status              TEXT NOT NULL DEFAULT 'queued',
    attempts            INTEGER NOT NULL DEFAULT 0,
    max_attempts        INTEGER NOT NULL DEFAULT 5,
    next_attempt_at     {t["timestamp"]} NOT NULL,
    locked_at           {t["timestamp"]},
    meta_message_id     TEXT UNIQUE,
    last_error          TEXT,
    sent_at             {t["timestamp"]},
    delivered_at        {t["timestamp"]},
    read_at             {t["timestamp"]},
    created_at          {t["timestamp"]} NOT NULL,
    updated_at          {t["timestamp"]} NOT NULL,
    CHECK (message_type IN ('text', 'template')),
    CHECK (status IN ('queued', 'processing', 'retrying', 'sent',
                      'delivered', 'read', 'failed'))
);
"""
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_due "
        "ON whatsapp_outbox(status, next_attempt_at)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_business "
        "ON whatsapp_outbox(business_id, created_at)"
    )


def _downgrade_whatsapp_outbox(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_whatsapp_outbox_business")
    conn.execute("DROP INDEX IF EXISTS idx_whatsapp_outbox_due")
    conn.execute("DROP TABLE IF EXISTS whatsapp_outbox")


def _upgrade_panel_layout(conn) -> None:
    # Guarda cómo cada negocio ordena/oculta los bloques de su panel de inicio.
    if "panel_layout" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN panel_layout TEXT")


def _downgrade_panel_layout(conn) -> None:
    # SQLite no soporta DROP COLUMN en versiones antiguas; se deja la columna
    # (es nullable y opcional, no rompe nada al revertir).
    if conn.dialect != "sqlite":
        conn.execute("ALTER TABLE businesses DROP COLUMN IF EXISTS panel_layout")


def _table_exists(conn, table: str) -> bool:
    if conn.dialect == "sqlite":
        row = conn.execute(
            "SELECT 1 AS found FROM sqlite_master "
            "WHERE type='table' AND name=?",
            (table,),
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT 1 AS found FROM information_schema.tables "
            "WHERE table_schema=current_schema() AND table_name=?",
            (table,),
        ).fetchone()
    return bool(row)


def _postgres_constraint_exists(conn, name: str) -> bool:
    if conn.dialect != "postgres":
        return False
    row = conn.execute(
        "SELECT 1 AS found FROM pg_constraint c "
        "JOIN pg_namespace n ON n.oid=c.connamespace "
        "WHERE n.nspname=current_schema() AND c.conname=?",
        (name,),
    ).fetchone()
    return bool(row)


def _upgrade_team_clockins(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS workers (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    name        TEXT NOT NULL,
    phone       TEXT,
    phone_norm  TEXT,
    color       TEXT,
    access_code TEXT NOT NULL,
    pin_hash    TEXT,
    active      {t["boolean"]} NOT NULL DEFAULT TRUE,
    created_at  {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, id),
    UNIQUE (business_id, access_code)
);
"""
    )
    if "worker_id" not in _column_names(conn, "jobs"):
        conn.execute(f"ALTER TABLE jobs ADD COLUMN worker_id {t['ref']}")

    # La FK compuesta de fichajes necesita una clave única por negocio en jobs.
    for statement in INDEXES:
        table = statement.split(" ON ", 1)[1].split("(", 1)[0].strip()
        if _table_exists(conn, table):
            conn.execute(statement)

    if conn.dialect == "postgres" and not _postgres_constraint_exists(
        conn, "jobs_worker_same_business"
    ):
        conn.execute(
            "ALTER TABLE jobs ADD CONSTRAINT jobs_worker_same_business "
            "FOREIGN KEY (business_id, worker_id) "
            "REFERENCES workers(business_id, id)"
        )

    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS worker_clockins (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    worker_id   {t["ref"]} NOT NULL,
    job_id      {t["ref"]},
    action      TEXT NOT NULL CHECK (action IN ('entrada', 'salida')),
    at          {t["timestamp"]} NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('web', 'whatsapp')),
    lat         {t["real"]},
    lng         {t["real"]},
    accuracy    {t["real"]},
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id),
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id)
);

CREATE TABLE IF NOT EXISTS worker_tokens (
    token       TEXT PRIMARY KEY,
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    worker_id   {t["ref"]} NOT NULL,
    expires_at  {t["timestamp"]} NOT NULL,
    revoked     {t["boolean"]} NOT NULL DEFAULT FALSE,
    created_at  {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id)
);
"""
    )
    for statement in INDEXES:
        table = statement.split(" ON ", 1)[1].split("(", 1)[0].strip()
        if _table_exists(conn, table):
            conn.execute(statement)

    if conn.dialect == "sqlite":
        for event in ("INSERT", "UPDATE"):
            conn.executescript(
                _sqlite_tenant_trigger("jobs", "worker_id", "workers", event)
            )


def _downgrade_team_clockins(conn) -> None:
    if conn.dialect == "sqlite":
        conn.execute("UPDATE jobs SET worker_id=NULL")
        conn.execute("DROP TRIGGER IF EXISTS jobs_worker_id_same_business_insert")
        conn.execute("DROP TRIGGER IF EXISTS jobs_worker_id_same_business_update")
    else:
        conn.execute(
            "ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_worker_same_business"
        )
    for name in (
        "idx_clockins_worker", "idx_jobs_worker", "idx_workers_business",
    ):
        conn.execute(f"DROP INDEX IF EXISTS {name}")
    conn.execute("DROP TABLE IF EXISTS worker_tokens")
    conn.execute("DROP TABLE IF EXISTS worker_clockins")
    conn.execute("DROP TABLE IF EXISTS workers")
    if conn.dialect != "sqlite":
        conn.execute("ALTER TABLE jobs DROP COLUMN IF EXISTS worker_id")


def _sqlite_rebuild_clockins_v6(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE worker_clockins_v6 (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    worker_id   {t["ref"]} NOT NULL,
    job_id      {t["ref"]},
    action      TEXT NOT NULL
                CHECK (action IN ('entrada', 'salida', 'pausa', 'reanudar')),
    at          {t["timestamp"]} NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('web', 'whatsapp')),
    lat         {t["real"]},
    lng         {t["real"]},
    accuracy    {t["real"]},
    created_at  {t["timestamp"]} NOT NULL,
    seal        TEXT,
    prev_seal   TEXT,
    FOREIGN KEY (business_id, worker_id)
        REFERENCES workers(business_id, id),
    FOREIGN KEY (business_id, job_id)
        REFERENCES jobs(business_id, id)
);
INSERT INTO worker_clockins_v6
    (id, business_id, worker_id, job_id, action, at, source, lat, lng,
     accuracy, created_at)
SELECT id, business_id, worker_id, job_id, action, at, source, lat, lng,
       accuracy, created_at
FROM worker_clockins;
DROP TABLE worker_clockins;
ALTER TABLE worker_clockins_v6 RENAME TO worker_clockins;
"""
    )


def _backfill_clockin_seals(conn) -> None:
    rows = conn.execute(
        "SELECT * FROM worker_clockins "
        "ORDER BY business_id, worker_id, id"
    ).fetchall()
    previous: dict[tuple[int, int], str | None] = {}
    for row in rows:
        key = (int(row["business_id"]), int(row["worker_id"]))
        prev_seal = previous.get(key)
        seal = clockin_seal(row, prev_seal)
        conn.execute(
            "UPDATE worker_clockins SET prev_seal=?, seal=? "
            "WHERE id=? AND business_id=?",
            (prev_seal, seal, row["id"], row["business_id"]),
        )
        previous[key] = seal


def _install_clockin_append_only(conn) -> None:
    if conn.dialect == "sqlite":
        conn.executescript(
            """
CREATE TRIGGER IF NOT EXISTS worker_clockins_require_seal
BEFORE INSERT ON worker_clockins
WHEN NEW.seal IS NULL OR NEW.seal=''
BEGIN
    SELECT RAISE(ABORT, 'todo fichaje necesita sello');
END;
CREATE TRIGGER IF NOT EXISTS worker_clockins_append_only_update
BEFORE UPDATE ON worker_clockins
BEGIN
    SELECT RAISE(ABORT, 'los fichajes son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS worker_clockins_append_only_delete
BEFORE DELETE ON worker_clockins
BEGIN
    SELECT RAISE(ABORT, 'los fichajes son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS clockin_corrections_append_only_update
BEFORE UPDATE ON worker_clockin_corrections
BEGIN
    SELECT RAISE(ABORT, 'las correcciones son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS clockin_corrections_append_only_delete
BEFORE DELETE ON worker_clockin_corrections
BEGIN
    SELECT RAISE(ABORT, 'las correcciones son inalterables');
END;
"""
        )
        return
    conn.execute(
        """
CREATE OR REPLACE FUNCTION noesis_clockins_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'los registros de jornada son inalterables';
END;
$$ LANGUAGE plpgsql
"""
    )
    for table in ("worker_clockins", "worker_clockin_corrections"):
        trigger = f"{table}_append_only"
        conn.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        conn.execute(
            f"CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION noesis_clockins_append_only()"
        )


def _upgrade_immutable_clockins(conn) -> None:
    t = _types(conn.dialect)
    if "clockin_policy" not in _column_names(conn, "businesses"):
        conn.execute("ALTER TABLE businesses ADD COLUMN clockin_policy TEXT")

    columns = _column_names(conn, "worker_clockins")
    if conn.dialect == "sqlite" and "seal" not in columns:
        _sqlite_rebuild_clockins_v6(conn)
    elif conn.dialect == "postgres":
        if "seal" not in columns:
            conn.execute("ALTER TABLE worker_clockins ADD COLUMN seal TEXT")
        if "prev_seal" not in columns:
            conn.execute("ALTER TABLE worker_clockins ADD COLUMN prev_seal TEXT")
        conn.execute(
            "ALTER TABLE worker_clockins "
            "DROP CONSTRAINT IF EXISTS worker_clockins_action_check"
        )
        conn.execute(
            "ALTER TABLE worker_clockins ADD CONSTRAINT "
            "worker_clockins_action_check CHECK "
            "(action IN ('entrada', 'salida', 'pausa', 'reanudar'))"
        )

    _backfill_clockin_seals(conn)
    if conn.dialect == "postgres":
        conn.execute("ALTER TABLE worker_clockins ALTER COLUMN seal SET NOT NULL")

    for statement in INDEXES:
        table = statement.split(" ON ", 1)[1].split("(", 1)[0].strip()
        if _table_exists(conn, table):
            conn.execute(statement)

    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS worker_clockin_corrections (
    id             {t["id"]},
    business_id    {t["ref"]} NOT NULL REFERENCES businesses(id),
    clockin_id     {t["ref"]} NOT NULL,
    author_user_id {t["ref"]} NOT NULL REFERENCES users(id),
    reason         TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'corregido'
                   CHECK (status IN ('corregido', 'anulado')),
    old_at         {t["timestamp"]},
    new_at         {t["timestamp"]},
    created_at     {t["timestamp"]} NOT NULL,
    FOREIGN KEY (business_id, clockin_id)
        REFERENCES worker_clockins(business_id, id)
);
"""
    )
    for statement in INDEXES:
        table = statement.split(" ON ", 1)[1].split("(", 1)[0].strip()
        if _table_exists(conn, table):
            conn.execute(statement)
    _install_clockin_append_only(conn)


def _downgrade_immutable_clockins(conn) -> None:
    if conn.dialect == "sqlite":
        for trigger in (
            "worker_clockins_require_seal",
            "worker_clockins_append_only_update",
            "worker_clockins_append_only_delete",
            "clockin_corrections_append_only_update",
            "clockin_corrections_append_only_delete",
        ):
            conn.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    else:
        for table in ("worker_clockins", "worker_clockin_corrections"):
            conn.execute(
                f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}"
            )
        conn.execute("DROP FUNCTION IF EXISTS noesis_clockins_append_only()")
    conn.execute("DROP INDEX IF EXISTS idx_clockin_corrections_clockin")
    conn.execute("DROP TABLE IF EXISTS worker_clockin_corrections")
    # Las columnas y el CHECK ampliado se conservan: eliminarlos podría destruir
    # sellos o hacer imposible revertir si ya existen pausas.


def _install_invoice_append_only(conn) -> None:
    tables = ("invoice_records", "invoice_events")
    if conn.dialect == "sqlite":
        for table in tables:
            conn.executescript(
                f"""
CREATE TRIGGER IF NOT EXISTS {table}_append_only_update
BEFORE UPDATE ON {table}
BEGIN
    SELECT RAISE(ABORT, 'los registros VeriFactu son inalterables');
END;
CREATE TRIGGER IF NOT EXISTS {table}_append_only_delete
BEFORE DELETE ON {table}
BEGIN
    SELECT RAISE(ABORT, 'los registros VeriFactu son inalterables');
END;
"""
            )
        conn.executescript(
            """
CREATE TRIGGER IF NOT EXISTS invoice_records_require_hash
BEFORE INSERT ON invoice_records
WHEN NEW.record_hash IS NULL OR NEW.record_hash=''
BEGIN
    SELECT RAISE(ABORT, 'todo registro VeriFactu necesita huella');
END;
"""
        )
        return
    conn.execute(
        """
CREATE OR REPLACE FUNCTION noesis_invoice_records_append_only()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'los registros VeriFactu son inalterables';
END;
$$ LANGUAGE plpgsql
"""
    )
    for table in tables:
        trigger = f"{table}_append_only"
        conn.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        conn.execute(
            f"CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION noesis_invoice_records_append_only()"
        )


def _upgrade_verifactu_phase1(conn) -> None:
    t = _types(conn.dialect)
    business_columns = _column_names(conn, "businesses")
    if "verifactu_enabled" not in business_columns:
        conn.execute(
            "ALTER TABLE businesses ADD COLUMN "
            f"verifactu_enabled {t['boolean']} NOT NULL DEFAULT FALSE"
        )

    invoice_columns = _column_names(conn, "invoices")
    additions = (
        ("invoice_type", "TEXT NOT NULL DEFAULT 'F1'"),
        ("rectifies_invoice_id", t["ref"]),
        ("rectification_type", "TEXT"),
        ("rectification_reason", "TEXT"),
    )
    for column, definition in additions:
        if column not in invoice_columns:
            conn.execute(
                f"ALTER TABLE invoices ADD COLUMN {column} {definition}"
            )

    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS invoice_records (
    id                       {t["id"]},
    business_id              {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id               {t["ref"]} NOT NULL,
    record_type              TEXT NOT NULL DEFAULT 'alta'
                             CHECK (record_type IN ('alta')),
    record_version           TEXT NOT NULL,
    invoice_type             TEXT NOT NULL,
    rectification_type       TEXT,
    rectified_issuer_nif     TEXT,
    rectified_invoice_number TEXT,
    rectified_issue_date     TEXT,
    issuer_nif               TEXT NOT NULL,
    issuer_name              TEXT NOT NULL,
    invoice_number           TEXT NOT NULL,
    issue_date               TEXT NOT NULL,
    recipient_nif            TEXT NOT NULL,
    recipient_name           TEXT NOT NULL,
    description              TEXT NOT NULL,
    breakdown_json           TEXT NOT NULL,
    vat_total                {t["real"]} NOT NULL,
    invoice_total            {t["real"]} NOT NULL,
    generated_at             TEXT NOT NULL,
    previous_record_id       {t["ref"]},
    previous_issuer_nif      TEXT,
    previous_invoice_number  TEXT,
    previous_issue_date      TEXT,
    previous_hash            TEXT,
    hash_algorithm           TEXT NOT NULL,
    hash_type                TEXT NOT NULL,
    hash_spec_version        TEXT NOT NULL,
    record_hash              TEXT NOT NULL,
    qr_url                   TEXT NOT NULL,
    producer_name            TEXT NOT NULL,
    producer_nif             TEXT NOT NULL,
    system_name              TEXT NOT NULL,
    system_id                TEXT NOT NULL,
    system_version           TEXT NOT NULL,
    installation_id          TEXT NOT NULL,
    created_at               TEXT NOT NULL,
    UNIQUE (business_id, id),
    UNIQUE (business_id, invoice_id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, previous_record_id)
        REFERENCES invoice_records(business_id, id)
);

CREATE TABLE IF NOT EXISTS invoice_events (
    id          {t["id"]},
    business_id {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id  {t["ref"]},
    record_id   {t["ref"]},
    event_type  TEXT NOT NULL
                CHECK (event_type IN
                    ('alta', 'rectificacion', 'exportacion', 'anomalia')),
    details     TEXT,
    created_at  TEXT NOT NULL,
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, record_id)
        REFERENCES invoice_records(business_id, id)
);
"""
    )
    for statement in INDEXES:
        table = statement.split(" ON ", 1)[1].split("(", 1)[0].strip()
        if _table_exists(conn, table):
            conn.execute(statement)
    _install_invoice_append_only(conn)


def _downgrade_verifactu_phase1(conn) -> None:
    if conn.dialect == "sqlite":
        for trigger in (
            "invoice_records_append_only_update",
            "invoice_records_append_only_delete",
            "invoice_events_append_only_update",
            "invoice_events_append_only_delete",
            "invoice_records_require_hash",
        ):
            conn.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    else:
        for table in ("invoice_records", "invoice_events"):
            conn.execute(
                f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}"
            )
        conn.execute(
            "DROP FUNCTION IF EXISTS noesis_invoice_records_append_only()"
        )
    conn.execute("DROP INDEX IF EXISTS idx_invoice_events_business")
    conn.execute("DROP INDEX IF EXISTS idx_invoice_records_issuer")
    conn.execute("DROP TABLE IF EXISTS invoice_events")
    conn.execute("DROP TABLE IF EXISTS invoice_records")
    # Las columnas se conservan para no perder la relación de rectificativas ni
    # reactivar accidentalmente un modo que el negocio hubiera desactivado.


def _upgrade_verified_backups(conn) -> None:
    t = _types(conn.dialect)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS backup_runs (
    id          {t["id"]},
    created_at  {t["timestamp"]} NOT NULL,
    filename    TEXT,
    size_bytes  BIGINT NOT NULL DEFAULT 0,
    status      TEXT NOT NULL CHECK (status IN ('ok', 'error')),
    storage     TEXT NOT NULL,
    error       TEXT
);
CREATE INDEX IF NOT EXISTS idx_backup_runs_created
    ON backup_runs(created_at);
"""
    )


def _downgrade_verified_backups(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_backup_runs_created")
    conn.execute("DROP TABLE IF EXISTS backup_runs")


def _expand_invoice_event_types(conn) -> None:
    """Añade eventos de remisión sin alterar nunca los eventos existentes."""
    allowed = (
        "'alta', 'rectificacion', 'exportacion', 'anomalia', "
        "'remision', 'aceptacion', 'rechazo'"
    )
    if conn.dialect == "sqlite":
        conn.execute("DROP TRIGGER IF EXISTS invoice_events_append_only_update")
        conn.execute("DROP TRIGGER IF EXISTS invoice_events_append_only_delete")
        conn.execute("DROP INDEX IF EXISTS idx_invoice_events_business")
        conn.executescript(
            f"""
CREATE TABLE invoice_events_v9 (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL REFERENCES businesses(id),
    invoice_id  INTEGER,
    record_id   INTEGER,
    event_type  TEXT NOT NULL CHECK (event_type IN ({allowed})),
    details     TEXT,
    created_at  TEXT NOT NULL,
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, record_id)
        REFERENCES invoice_records(business_id, id)
);
INSERT INTO invoice_events_v9
    (id, business_id, invoice_id, record_id, event_type, details, created_at)
SELECT id, business_id, invoice_id, record_id, event_type, details, created_at
FROM invoice_events;
DROP TABLE invoice_events;
ALTER TABLE invoice_events_v9 RENAME TO invoice_events;
"""
        )
    else:
        conn.execute(
            "ALTER TABLE invoice_events DROP CONSTRAINT IF EXISTS "
            "invoice_events_event_type_check"
        )
        conn.execute(
            "ALTER TABLE invoice_events ADD CONSTRAINT "
            f"invoice_events_event_type_check CHECK (event_type IN ({allowed}))"
        )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_invoice_events_business "
        "ON invoice_events(business_id, created_at, id)"
    )
    _install_invoice_append_only(conn)


def _upgrade_verifactu_phase2(conn) -> None:
    t = _types(conn.dialect)
    _expand_invoice_event_types(conn)
    conn.executescript(
        f"""
CREATE TABLE IF NOT EXISTS verifactu_outbox (
    id                    {t["id"]},
    business_id           {t["ref"]} NOT NULL REFERENCES businesses(id),
    invoice_id            {t["ref"]} NOT NULL,
    record_id             {t["ref"]} NOT NULL,
    status                TEXT NOT NULL DEFAULT 'pendiente'
                          CHECK (status IN (
                              'pendiente', 'enviado', 'aceptado',
                              'aceptado_con_errores', 'rechazado'
                          )),
    attempts              INTEGER NOT NULL DEFAULT 0,
    max_attempts          INTEGER NOT NULL DEFAULT 6,
    next_attempt_at       {t["timestamp"]} NOT NULL,
    locked_at             {t["timestamp"]},
    sent_at               {t["timestamp"]},
    completed_at          {t["timestamp"]},
    aeat_csv              TEXT,
    aeat_global_status    TEXT,
    aeat_error_code       TEXT,
    aeat_error_description TEXT,
    aeat_response         TEXT,
    wait_seconds          INTEGER NOT NULL DEFAULT 0,
    last_error            TEXT,
    created_at            {t["timestamp"]} NOT NULL,
    updated_at            {t["timestamp"]} NOT NULL,
    UNIQUE (business_id, record_id),
    FOREIGN KEY (business_id, invoice_id)
        REFERENCES invoices(business_id, id),
    FOREIGN KEY (business_id, record_id)
        REFERENCES invoice_records(business_id, id)
);
CREATE INDEX IF NOT EXISTS idx_verifactu_outbox_due
    ON verifactu_outbox(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_verifactu_outbox_business
    ON verifactu_outbox(business_id, invoice_id, id);
"""
    )


def _downgrade_verifactu_phase2(conn) -> None:
    conn.execute("DROP INDEX IF EXISTS idx_verifactu_outbox_business")
    conn.execute("DROP INDEX IF EXISTS idx_verifactu_outbox_due")
    conn.execute("DROP TABLE IF EXISTS verifactu_outbox")
    # Los nuevos eventos se conservan: estrechar el CHECK podría destruir auditoría.


Migration = tuple[int, str, Callable, Callable]
MIGRATIONS: tuple[Migration, ...] = (
    (1, "esquema_inicial", _upgrade_initial, _downgrade_initial),
    (2, "integridad_multiempresa", _upgrade_tenant_integrity, _downgrade_tenant_integrity),
    (3, "cola_whatsapp_durable", _upgrade_whatsapp_outbox, _downgrade_whatsapp_outbox),
    (4, "panel_personalizable", _upgrade_panel_layout, _downgrade_panel_layout),
    (5, "equipo_fichaje", _upgrade_team_clockins, _downgrade_team_clockins),
    (6, "fichaje_inalterable", _upgrade_immutable_clockins, _downgrade_immutable_clockins),
    (7, "verifactu_fase1", _upgrade_verifactu_phase1, _downgrade_verifactu_phase1),
    (8, "backups_verificados", _upgrade_verified_backups, _downgrade_verified_backups),
    (9, "verifactu_fase2", _upgrade_verifactu_phase2, _downgrade_verifactu_phase2),
)
LATEST_VERSION = MIGRATIONS[-1][0]


def _ensure_version_table(conn) -> None:
    timestamp = _types(conn.dialect)["timestamp"]
    conn.execute(
        "CREATE TABLE IF NOT EXISTS schema_migrations ("
        "version INTEGER PRIMARY KEY, name TEXT NOT NULL, "
        f"applied_at {timestamp} NOT NULL)"
    )


def _version_table_exists(conn) -> bool:
    if conn.dialect == "sqlite":
        row = conn.execute(
            "SELECT 1 AS found FROM sqlite_master "
            "WHERE type='table' AND name='schema_migrations'"
        ).fetchone()
    else:
        row = conn.execute(
            "SELECT 1 AS found FROM information_schema.tables "
            "WHERE table_schema=current_schema() "
            "AND table_name='schema_migrations'"
        ).fetchone()
    return bool(row)


def _current_version(conn) -> int:
    if not _version_table_exists(conn):
        return 0
    row = conn.execute(
        "SELECT COALESCE(MAX(version), 0) AS version FROM schema_migrations"
    ).fetchone()
    return int(row["version"])


def current_version() -> int:
    from . import db

    with db.get_conn() as conn:
        return _current_version(conn)


def current_version_connection(conn) -> int:
    """Consulta la versión dentro de una conexión o esquema ya seleccionado."""
    return _current_version(conn)


def is_current() -> bool:
    try:
        return current_version() == LATEST_VERSION
    except Exception:
        return False


def upgrade_connection(conn, target: int | None = None) -> int:
    """Aplica migraciones sobre una conexión existente.

    La restauración de Postgres la usa con un ``search_path`` temporal para no
    escribir nunca en el esquema real durante la verificación.
    """
    target = LATEST_VERSION if target is None else target
    if target < 0 or target > LATEST_VERSION:
        raise ValueError(f"Versión objetivo no válida: {target}")
    _ensure_version_table(conn)
    current = _current_version(conn)
    for version, name, apply, _revert in MIGRATIONS:
        if current < version <= target:
            apply(conn)
            conn.execute(
                "INSERT INTO schema_migrations (version, name, applied_at) "
                "VALUES (?, ?, ?)",
                (version, name, datetime.now().isoformat(timespec="seconds")),
            )
            current = version
    return current


def upgrade(target: int | None = None) -> int:
    from . import db

    with db.get_conn() as conn:
        current = upgrade_connection(conn, target)
    return current


def downgrade(target: int | None = None) -> int:
    from . import db

    with db.get_conn() as conn:
        current = _current_version(conn)
        target = max(0, current - 1) if target is None else target
        if target < 0 or target >= current:
            raise ValueError(f"Versión objetivo no válida: {target}")
        for version, _name, _apply, revert in reversed(MIGRATIONS):
            if target < version <= current:
                revert(conn)
                conn.execute(
                    "DELETE FROM schema_migrations WHERE version=?", (version,)
                )
        return target


def main() -> None:
    parser = argparse.ArgumentParser(description="Migraciones de Noesis")
    parser.add_argument("action", choices=("upgrade", "downgrade", "current"))
    parser.add_argument("target", nargs="?", type=int)
    args = parser.parse_args()
    if args.action == "upgrade":
        version = upgrade(args.target)
    elif args.action == "downgrade":
        version = downgrade(args.target)
    else:
        version = current_version()
    print(f"Esquema en versión {version}/{LATEST_VERSION}")


if __name__ == "__main__":
    main()
