"""Referencia main 6b4c144; valores públicos y huellas de fixtures sintéticas."""

REFERENCE = {'baseline': '6b4c1446bdb689555ed6094ffdbcd7101a325404',  # pragma: allowlist secret - huella sintética pública
 'schema': 63,
 'result': [{'invoice': {'id': 1,
                         'business_id': 1,
                         'number': '2026/0001',
                         'client_id': 1,
                         'concept': '21 y 3 línea(s) más',
                         'base': 40.2,
                         'vat_rate': -1.0,
                         'vat_amount': 3.52,
                         'irpf_rate': 15.0,
                         'irpf_amount': 6.03,
                         'total': 37.69,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'F1',
                         'rectifies_invoice_id': None,
                         'rectification_type': None,
                         'rectification_reason': None,
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 1,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 37.69,
                         'payment_status': 'pendiente',
                         'lines': [{'id': 1,
                                    'business_id': 1,
                                    'invoice_id': 1,
                                    'position': 1,
                                    'description': '21',
                                    'quantity': 1.0,
                                    'unit_price': 10.05,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': 10.05,
                                    'vat_amount': 2.11,
                                    'total': 12.16,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'},
                                   {'id': 2,
                                    'business_id': 1,
                                    'invoice_id': 1,
                                    'position': 2,
                                    'description': '10',
                                    'quantity': 1.0,
                                    'unit_price': 10.05,
                                    'discount_rate': 0.0,
                                    'vat_rate': 10.0,
                                    'base': 10.05,
                                    'vat_amount': 1.01,
                                    'total': 11.06,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'},
                                   {'id': 3,
                                    'business_id': 1,
                                    'invoice_id': 1,
                                    'position': 3,
                                    'description': '4',
                                    'quantity': 1.0,
                                    'unit_price': 10.05,
                                    'discount_rate': 0.0,
                                    'vat_rate': 4.0,
                                    'base': 10.05,
                                    'vat_amount': 0.4,
                                    'total': 10.45,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'},
                                   {'id': 4,
                                    'business_id': 1,
                                    'invoice_id': 1,
                                    'position': 4,
                                    'description': '0',
                                    'quantity': 1.0,
                                    'unit_price': 10.05,
                                    'discount_rate': 0.0,
                                    'vat_rate': 0.0,
                                    'base': 10.05,
                                    'vat_amount': 0.0,
                                    'total': 10.05,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 1,
                        'business_id': 1,
                        'invoice_id': 1,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'F1',
                        'rectification_type': None,
                        'rectified_issuer_nif': None,
                        'rectified_invoice_number': None,
                        'rectified_issue_date': None,
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': '2026/0001',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': '21 y 3 línea(s) más',
                        'breakdown_json': '[{"vat_rate":0.0,"base":10.05,"vat_amount":0.0},{"vat_rate":4.0,"base":10.05,"vat_amount":0.4},{"vat_rate":10.0,"base":10.05,"vat_amount":1.01},{"vat_rate":21.0,"base":10.05,"vat_amount":2.11}]',
                        'vat_total': 3.52,
                        'invoice_total': 37.69,
                        'generated_at': '2026-10-02T10:00:00+02:00',
                        'previous_record_id': None,
                        'previous_issuer_nif': None,
                        'previous_invoice_number': None,
                        'previous_issue_date': None,
                        'previous_hash': None,
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': '190B89DFE4220E7E50AD6E629A36F888CD52DDB3DA98723D43A025EED75A326E',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=2026%2F0001&fecha=02-10-2026&importe=37.69',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00+02:00',
                        'operation_date': None}},
            {'invoice': {'id': 2,
                         'business_id': 1,
                         'number': 'T2026/0001',
                         'client_id': 1,
                         'concept': 'Ticket',
                         'base': 100.0,
                         'vat_rate': 21.0,
                         'vat_amount': 21.0,
                         'irpf_rate': 0.0,
                         'irpf_amount': 0.0,
                         'total': 121.0,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'F2',
                         'rectifies_invoice_id': None,
                         'rectification_type': None,
                         'rectification_reason': None,
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 2,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 121.0,
                         'payment_status': 'pendiente',
                         'lines': [{'id': 5,
                                    'business_id': 1,
                                    'invoice_id': 2,
                                    'position': 1,
                                    'description': 'Ticket',
                                    'quantity': 1.0,
                                    'unit_price': 100.0,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': 100.0,
                                    'vat_amount': 21.0,
                                    'total': 121.0,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 2,
                        'business_id': 1,
                        'invoice_id': 2,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'F2',
                        'rectification_type': None,
                        'rectified_issuer_nif': None,
                        'rectified_invoice_number': None,
                        'rectified_issue_date': None,
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': 'T2026/0001',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': 'Ticket',
                        'breakdown_json': '[{"vat_rate":21.0,"base":100.0,"vat_amount":21.0}]',
                        'vat_total': 21.0,
                        'invoice_total': 121.0,
                        'generated_at': '2026-10-02T10:00:00.001+02:00',
                        'previous_record_id': 1,
                        'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'previous_invoice_number': '2026/0001',
                        'previous_issue_date': '02-10-2026',
                        'previous_hash': '190B89DFE4220E7E50AD6E629A36F888CD52DDB3DA98723D43A025EED75A326E',  # pragma: allowlist secret - huella sintética pública
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': '56683D28DE78996FB67E1FC3EE51AF1BDBB92A393937D28A6A714F15FD714D0E',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=T2026%2F0001&fecha=02-10-2026&importe=121',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00.001+02:00',
                        'operation_date': None}},
            {'invoice': {'id': 3,
                         'business_id': 1,
                         'number': 'R2026/0001',
                         'client_id': 1,
                         'concept': 'Rectificación',
                         'base': -2.68,
                         'vat_rate': 21.0,
                         'vat_amount': -0.56,
                         'irpf_rate': 0.0,
                         'irpf_amount': 0.0,
                         'total': -3.24,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'R1',
                         'rectifies_invoice_id': 1,
                         'rectification_type': 'I',
                         'rectification_reason': 'Error de precio',
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 3,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 0,
                         'payment_status': 'pagada',
                         'lines': [{'id': 6,
                                    'business_id': 1,
                                    'invoice_id': 3,
                                    'position': 1,
                                    'description': 'Rectificación',
                                    'quantity': 1.0,
                                    'unit_price': -2.675,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': -2.68,
                                    'vat_amount': -0.56,
                                    'total': -3.24,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 3,
                        'business_id': 1,
                        'invoice_id': 3,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'R1',
                        'rectification_type': 'I',
                        'rectified_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'rectified_invoice_number': '2026/0001',
                        'rectified_issue_date': '02-10-2026',
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': 'R2026/0001',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': 'Rectificación',
                        'breakdown_json': '[{"vat_rate":21.0,"base":-2.68,"vat_amount":-0.56}]',
                        'vat_total': -0.56,
                        'invoice_total': -3.24,
                        'generated_at': '2026-10-02T10:00:00.002+02:00',
                        'previous_record_id': 2,
                        'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'previous_invoice_number': 'T2026/0001',
                        'previous_issue_date': '02-10-2026',
                        'previous_hash': '56683D28DE78996FB67E1FC3EE51AF1BDBB92A393937D28A6A714F15FD714D0E',  # pragma: allowlist secret - huella sintética pública
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': '0898772010C938178054E9C8C711ED14B929A48F2599F1E50912E75764698AF1',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=R2026%2F0001&fecha=02-10-2026&importe=-3.24',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00.002+02:00',
                        'operation_date': None}},
            {'invoice': {'id': 4,
                         'business_id': 1,
                         'number': 'R2026/0002',
                         'client_id': 1,
                         'concept': 'Rectificación',
                         'base': -2.68,
                         'vat_rate': 21.0,
                         'vat_amount': -0.56,
                         'irpf_rate': 0.0,
                         'irpf_amount': 0.0,
                         'total': -3.24,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'R2',
                         'rectifies_invoice_id': 1,
                         'rectification_type': 'I',
                         'rectification_reason': 'Error de precio',
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 3,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 0,
                         'payment_status': 'pagada',
                         'lines': [{'id': 7,
                                    'business_id': 1,
                                    'invoice_id': 4,
                                    'position': 1,
                                    'description': 'Rectificación',
                                    'quantity': 1.0,
                                    'unit_price': -2.675,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': -2.68,
                                    'vat_amount': -0.56,
                                    'total': -3.24,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 4,
                        'business_id': 1,
                        'invoice_id': 4,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'R2',
                        'rectification_type': 'I',
                        'rectified_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'rectified_invoice_number': '2026/0001',
                        'rectified_issue_date': '02-10-2026',
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': 'R2026/0002',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': 'Rectificación',
                        'breakdown_json': '[{"vat_rate":21.0,"base":-2.68,"vat_amount":-0.56}]',
                        'vat_total': -0.56,
                        'invoice_total': -3.24,
                        'generated_at': '2026-10-02T10:00:00.003+02:00',
                        'previous_record_id': 3,
                        'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'previous_invoice_number': 'R2026/0001',
                        'previous_issue_date': '02-10-2026',
                        'previous_hash': '0898772010C938178054E9C8C711ED14B929A48F2599F1E50912E75764698AF1',  # pragma: allowlist secret - huella sintética pública
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': 'B1713D52385CF44C9BE914445E9DD5129AA23406B33546F79B0794BBEB124A98',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=R2026%2F0002&fecha=02-10-2026&importe=-3.24',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00.003+02:00',
                        'operation_date': None}},
            {'invoice': {'id': 5,
                         'business_id': 1,
                         'number': 'R2026/0003',
                         'client_id': 1,
                         'concept': 'Rectificación',
                         'base': -2.68,
                         'vat_rate': 21.0,
                         'vat_amount': -0.56,
                         'irpf_rate': 0.0,
                         'irpf_amount': 0.0,
                         'total': -3.24,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'R3',
                         'rectifies_invoice_id': 1,
                         'rectification_type': 'I',
                         'rectification_reason': 'Error de precio',
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 3,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 0,
                         'payment_status': 'pagada',
                         'lines': [{'id': 8,
                                    'business_id': 1,
                                    'invoice_id': 5,
                                    'position': 1,
                                    'description': 'Rectificación',
                                    'quantity': 1.0,
                                    'unit_price': -2.675,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': -2.68,
                                    'vat_amount': -0.56,
                                    'total': -3.24,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 5,
                        'business_id': 1,
                        'invoice_id': 5,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'R3',
                        'rectification_type': 'I',
                        'rectified_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'rectified_invoice_number': '2026/0001',
                        'rectified_issue_date': '02-10-2026',
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': 'R2026/0003',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': 'Rectificación',
                        'breakdown_json': '[{"vat_rate":21.0,"base":-2.68,"vat_amount":-0.56}]',
                        'vat_total': -0.56,
                        'invoice_total': -3.24,
                        'generated_at': '2026-10-02T10:00:00.004+02:00',
                        'previous_record_id': 4,
                        'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'previous_invoice_number': 'R2026/0002',
                        'previous_issue_date': '02-10-2026',
                        'previous_hash': 'B1713D52385CF44C9BE914445E9DD5129AA23406B33546F79B0794BBEB124A98',  # pragma: allowlist secret - huella sintética pública
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': '17A2600C80027620BDD807A86EF3208BF504B0A77A96627AD743815F29493016',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=R2026%2F0003&fecha=02-10-2026&importe=-3.24',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00.004+02:00',
                        'operation_date': None}},
            {'invoice': {'id': 6,
                         'business_id': 1,
                         'number': 'R2026/0004',
                         'client_id': 1,
                         'concept': 'Rectificación',
                         'base': -2.68,
                         'vat_rate': 21.0,
                         'vat_amount': -0.56,
                         'irpf_rate': 0.0,
                         'irpf_amount': 0.0,
                         'total': -3.24,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'R4',
                         'rectifies_invoice_id': 1,
                         'rectification_type': 'I',
                         'rectification_reason': 'Error de precio',
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 3,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 0,
                         'payment_status': 'pagada',
                         'lines': [{'id': 9,
                                    'business_id': 1,
                                    'invoice_id': 6,
                                    'position': 1,
                                    'description': 'Rectificación',
                                    'quantity': 1.0,
                                    'unit_price': -2.675,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': -2.68,
                                    'vat_amount': -0.56,
                                    'total': -3.24,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 6,
                        'business_id': 1,
                        'invoice_id': 6,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'R4',
                        'rectification_type': 'I',
                        'rectified_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'rectified_invoice_number': '2026/0001',
                        'rectified_issue_date': '02-10-2026',
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': 'R2026/0004',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': 'Rectificación',
                        'breakdown_json': '[{"vat_rate":21.0,"base":-2.68,"vat_amount":-0.56}]',
                        'vat_total': -0.56,
                        'invoice_total': -3.24,
                        'generated_at': '2026-10-02T10:00:00.005+02:00',
                        'previous_record_id': 5,
                        'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'previous_invoice_number': 'R2026/0003',
                        'previous_issue_date': '02-10-2026',
                        'previous_hash': '17A2600C80027620BDD807A86EF3208BF504B0A77A96627AD743815F29493016',  # pragma: allowlist secret - huella sintética pública
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': '4CB82603347C55CED66A8FB94C414DE3B889EAB52784BA32818E32C178748F41',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=R2026%2F0004&fecha=02-10-2026&importe=-3.24',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00.005+02:00',
                        'operation_date': None}},
            {'invoice': {'id': 7,
                         'business_id': 1,
                         'number': 'R2026/0005',
                         'client_id': 1,
                         'concept': 'Rectificación',
                         'base': -2.68,
                         'vat_rate': 21.0,
                         'vat_amount': -0.56,
                         'irpf_rate': 0.0,
                         'irpf_amount': 0.0,
                         'total': -3.24,
                         'status': 'enviada',
                         'due_date': '2026-10-17',
                         'issued_at': '2026-10-02T10:00:00',
                         'paid_at': None,
                         'last_reminder_at': None,
                         'reminders_sent': 0,
                         'issuer_name': 'Frontera',
                         'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                         'issuer_address': 'Calle 1',
                         'recipient_name': 'Cliente',
                         'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                         'recipient_address': 'Calle 2',
                         'created_at': '2026-10-02T10:00:00',
                         'invoice_type': 'R5',
                         'rectifies_invoice_id': 2,
                         'rectification_type': 'I',
                         'rectification_reason': 'Error de precio',
                         'source': 'noesis',
                         'external_number': None,
                         'series_id': 3,
                         'operation_date': None,
                         'notes': None,
                         'payment_method': None,
                         'legal_mention': None,
                         'currency': 'EUR',
                         'internal_note': None,
                         'document_profile_id': 1,
                         'pending_fields': None,
                         'client_name': 'Cliente',
                         'paid_amount': 0.0,
                         'remaining_amount': 0,
                         'payment_status': 'pagada',
                         'lines': [{'id': 10,
                                    'business_id': 1,
                                    'invoice_id': 7,
                                    'position': 1,
                                    'description': 'Rectificación',
                                    'quantity': 1.0,
                                    'unit_price': -2.675,
                                    'discount_rate': 0.0,
                                    'vat_rate': 21.0,
                                    'base': -2.68,
                                    'vat_amount': -0.56,
                                    'total': -3.24,
                                    'created_at': '2026-10-02T10:00:00',
                                    'kind': 'servicio'}]},
             'record': {'id': 7,
                        'business_id': 1,
                        'invoice_id': 7,
                        'record_type': 'alta',
                        'record_version': '1.0',
                        'invoice_type': 'R5',
                        'rectification_type': 'I',
                        'rectified_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'rectified_invoice_number': 'T2026/0001',
                        'rectified_issue_date': '02-10-2026',
                        'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'issuer_name': 'Frontera',
                        'invoice_number': 'R2026/0005',
                        'issue_date': '02-10-2026',
                        'recipient_nif': 'B12345674',  # pragma: allowlist secret - NIF de fixture sintética
                        'recipient_name': 'Cliente',
                        'description': 'Rectificación',
                        'breakdown_json': '[{"vat_rate":21.0,"base":-2.68,"vat_amount":-0.56}]',
                        'vat_total': -0.56,
                        'invoice_total': -3.24,
                        'generated_at': '2026-10-02T10:00:00.006+02:00',
                        'previous_record_id': 6,
                        'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                        'previous_invoice_number': 'R2026/0004',
                        'previous_issue_date': '02-10-2026',
                        'previous_hash': '4CB82603347C55CED66A8FB94C414DE3B889EAB52784BA32818E32C178748F41',  # pragma: allowlist secret - huella sintética pública
                        'hash_algorithm': 'sha256',
                        'hash_type': '01',
                        'hash_spec_version': '0.1.2',
                        'record_hash': '92A0B50EE325DAB16E7F41D4C66B79F6EC3F2E119B1B943EAFD4308EBD170900',  # pragma: allowlist secret - huella sintética pública
                        'qr_url': 'https://www2.agenciatributaria.gob.es/wlpl/TIKE-CONT/ValidarQR?nif=A12345678&numserie=R2026%2F0005&fecha=02-10-2026&importe=-3.24',  # pragma: allowlist secret - NIF de fixture sintética
                        'producer_name': 'Bynoesis',
                        'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                        'system_name': 'Bynoesis',
                        'system_id': 'NO',
                        'system_version': '0.1.0',
                        'installation_id': 'noesis-1',
                        'created_at': '2026-10-02T10:00:00.006+02:00',
                        'operation_date': None}},
            {'cancellation': {'id': 1,
                              'business_id': 1,
                              'invoice_id': 1,
                              'original_record_id': 1,
                              'record_type': 'anulacion',
                              'record_version': '1.0',
                              'issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                              'issuer_name': 'Frontera',
                              'invoice_number': '2026/0001',
                              'issue_date': '02-10-2026',
                              'reason': 'Error confirmado',
                              'generated_at': '2026-10-02T10:00:00.007+02:00',
                              'previous_record_type': 'alta',
                              'previous_record_id': 7,
                              'previous_issuer_nif': 'A12345678',  # pragma: allowlist secret - NIF de fixture sintética
                              'previous_invoice_number': 'R2026/0005',
                              'previous_issue_date': '02-10-2026',
                              'previous_hash': '92A0B50EE325DAB16E7F41D4C66B79F6EC3F2E119B1B943EAFD4308EBD170900',  # pragma: allowlist secret - huella sintética pública
                              'hash_algorithm': 'sha256',
                              'hash_type': '01',
                              'hash_spec_version': '0.1.2',
                              'record_hash': 'F72F1CE8ABF51CFF22E5110116BE63C5BA378BF6D19030155078D4C896DA51C8',  # pragma: allowlist secret - huella sintética pública
                              'producer_name': 'Bynoesis',
                              'producer_nif': 'B87654321',  # pragma: allowlist secret - NIF de fixture sintética
                              'system_name': 'Bynoesis',
                              'system_id': 'NO',
                              'system_version': '0.1.0',
                              'installation_id': 'noesis-1',
                              'created_at': '2026-10-02T10:00:00.007+02:00'},
             'xml': "<?xml version='1.0' encoding='utf-8'?>\n"
                    '<sum:RegFactuSistemaFacturacion '
                    'xmlns:sum="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroLR.xsd" '
                    'xmlns:sum1="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroInformacion.xsd"><sum:Cabecera><sum1:ObligadoEmision><sum1:NombreRazon>Frontera</sum1:NombreRazon><sum1:NIF>A12345678</sum1:NIF></sum1:ObligadoEmision></sum:Cabecera><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>F1</sum1:TipoFactura><sum1:DescripcionOperacion>21 '  # pragma: allowlist secret - NIF de fixture sintética
                    'y 3 línea(s) '
                    'más</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>0</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>10.05</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>0</sum1:CuotaRepercutida></sum1:DetalleDesglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>4</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>10.05</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>0.4</sum1:CuotaRepercutida></sum1:DetalleDesglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>10</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>10.05</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>1.01</sum1:CuotaRepercutida></sum1:DetalleDesglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>10.05</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>2.11</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>3.52</sum1:CuotaTotal><sum1:ImporteTotal>37.69</sum1:ImporteTotal><sum1:Encadenamiento><sum1:PrimerRegistro>S</sum1:PrimerRegistro></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>190B89DFE4220E7E50AD6E629A36F888CD52DDB3DA98723D43A025EED75A326E</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>T2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>F2</sum1:TipoFactura><sum1:DescripcionOperacion>Ticket</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>100</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>21</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>21</sum1:CuotaTotal><sum1:ImporteTotal>121</sum1:ImporteTotal><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>190B89DFE4220E7E50AD6E629A36F888CD52DDB3DA98723D43A025EED75A326E</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.001+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>56683D28DE78996FB67E1FC3EE51AF1BDBB92A393937D28A6A714F15FD714D0E</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>R1</sum1:TipoFactura><sum1:TipoRectificativa>I</sum1:TipoRectificativa><sum1:FacturasRectificadas><sum1:IDFacturaRectificada><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFacturaRectificada></sum1:FacturasRectificadas><sum1:DescripcionOperacion>Rectificación</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>-2.68</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>-0.56</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>-0.56</sum1:CuotaTotal><sum1:ImporteTotal>-3.24</sum1:ImporteTotal><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>T2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>56683D28DE78996FB67E1FC3EE51AF1BDBB92A393937D28A6A714F15FD714D0E</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.002+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>0898772010C938178054E9C8C711ED14B929A48F2599F1E50912E75764698AF1</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0002</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>R2</sum1:TipoFactura><sum1:TipoRectificativa>I</sum1:TipoRectificativa><sum1:FacturasRectificadas><sum1:IDFacturaRectificada><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFacturaRectificada></sum1:FacturasRectificadas><sum1:DescripcionOperacion>Rectificación</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>-2.68</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>-0.56</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>-0.56</sum1:CuotaTotal><sum1:ImporteTotal>-3.24</sum1:ImporteTotal><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>0898772010C938178054E9C8C711ED14B929A48F2599F1E50912E75764698AF1</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.003+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>B1713D52385CF44C9BE914445E9DD5129AA23406B33546F79B0794BBEB124A98</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0003</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>R3</sum1:TipoFactura><sum1:TipoRectificativa>I</sum1:TipoRectificativa><sum1:FacturasRectificadas><sum1:IDFacturaRectificada><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFacturaRectificada></sum1:FacturasRectificadas><sum1:DescripcionOperacion>Rectificación</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>-2.68</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>-0.56</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>-0.56</sum1:CuotaTotal><sum1:ImporteTotal>-3.24</sum1:ImporteTotal><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0002</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>B1713D52385CF44C9BE914445E9DD5129AA23406B33546F79B0794BBEB124A98</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.004+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>17A2600C80027620BDD807A86EF3208BF504B0A77A96627AD743815F29493016</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0004</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>R4</sum1:TipoFactura><sum1:TipoRectificativa>I</sum1:TipoRectificativa><sum1:FacturasRectificadas><sum1:IDFacturaRectificada><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFacturaRectificada></sum1:FacturasRectificadas><sum1:DescripcionOperacion>Rectificación</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>-2.68</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>-0.56</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>-0.56</sum1:CuotaTotal><sum1:ImporteTotal>-3.24</sum1:ImporteTotal><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0003</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>17A2600C80027620BDD807A86EF3208BF504B0A77A96627AD743815F29493016</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.005+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>4CB82603347C55CED66A8FB94C414DE3B889EAB52784BA32818E32C178748F41</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAlta><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0005</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFactura><sum1:NombreRazonEmisor>Frontera</sum1:NombreRazonEmisor><sum1:TipoFactura>R5</sum1:TipoFactura><sum1:TipoRectificativa>I</sum1:TipoRectificativa><sum1:FacturasRectificadas><sum1:IDFacturaRectificada><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>T2026/0001</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura></sum1:IDFacturaRectificada></sum1:FacturasRectificadas><sum1:DescripcionOperacion>Rectificación</sum1:DescripcionOperacion><sum1:Destinatarios><sum1:IDDestinatario><sum1:NombreRazon>Cliente</sum1:NombreRazon><sum1:NIF>B12345674</sum1:NIF></sum1:IDDestinatario></sum1:Destinatarios><sum1:Desglose><sum1:DetalleDesglose><sum1:Impuesto>01</sum1:Impuesto><sum1:ClaveRegimen>01</sum1:ClaveRegimen><sum1:CalificacionOperacion>S1</sum1:CalificacionOperacion><sum1:TipoImpositivo>21</sum1:TipoImpositivo><sum1:BaseImponibleOimporteNoSujeto>-2.68</sum1:BaseImponibleOimporteNoSujeto><sum1:CuotaRepercutida>-0.56</sum1:CuotaRepercutida></sum1:DetalleDesglose></sum1:Desglose><sum1:CuotaTotal>-0.56</sum1:CuotaTotal><sum1:ImporteTotal>-3.24</sum1:ImporteTotal><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0004</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>4CB82603347C55CED66A8FB94C414DE3B889EAB52784BA32818E32C178748F41</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.006+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>92A0B50EE325DAB16E7F41D4C66B79F6EC3F2E119B1B943EAFD4308EBD170900</sum1:Huella></sum1:RegistroAlta></sum:RegistroFactura><sum:RegistroFactura><sum1:RegistroAnulacion><sum1:IDVersion>1.0</sum1:IDVersion><sum1:IDFactura><sum1:IDEmisorFacturaAnulada>A12345678</sum1:IDEmisorFacturaAnulada><sum1:NumSerieFacturaAnulada>2026/0001</sum1:NumSerieFacturaAnulada><sum1:FechaExpedicionFacturaAnulada>02-10-2026</sum1:FechaExpedicionFacturaAnulada></sum1:IDFactura><sum1:Encadenamiento><sum1:RegistroAnterior><sum1:IDEmisorFactura>A12345678</sum1:IDEmisorFactura><sum1:NumSerieFactura>R2026/0005</sum1:NumSerieFactura><sum1:FechaExpedicionFactura>02-10-2026</sum1:FechaExpedicionFactura><sum1:Huella>92A0B50EE325DAB16E7F41D4C66B79F6EC3F2E119B1B943EAFD4308EBD170900</sum1:Huella></sum1:RegistroAnterior></sum1:Encadenamiento><sum1:SistemaInformatico><sum1:NombreRazon>Bynoesis</sum1:NombreRazon><sum1:NIF>B87654321</sum1:NIF><sum1:NombreSistemaInformatico>Bynoesis</sum1:NombreSistemaInformatico><sum1:IdSistemaInformatico>NO</sum1:IdSistemaInformatico><sum1:Version>0.1.0</sum1:Version><sum1:NumeroInstalacion>noesis-1</sum1:NumeroInstalacion><sum1:TipoUsoPosibleSoloVerifactu>N</sum1:TipoUsoPosibleSoloVerifactu><sum1:TipoUsoPosibleMultiOT>S</sum1:TipoUsoPosibleMultiOT><sum1:IndicadorMultiplesOT>S</sum1:IndicadorMultiplesOT></sum1:SistemaInformatico><sum1:FechaHoraHusoGenRegistro>2026-10-02T10:00:00.007+02:00</sum1:FechaHoraHusoGenRegistro><sum1:TipoHuella>01</sum1:TipoHuella><sum1:Huella>F72F1CE8ABF51CFF22E5110116BE63C5BA378BF6D19030155078D4C896DA51C8</sum1:Huella></sum1:RegistroAnulacion></sum:RegistroFactura></sum:RegFactuSistemaFacturacion>'}]}  # pragma: allowlist secret - huella sintética pública
